apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cpho-postgres-cluster-object-storage
  namespace: server
  labels:
    app: postgres-cluster-object-storage
  annotations:
    proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:15.4
  instances: 3
  startDelay: 900
  stopDelay: 900
  primaryUpdateStrategy: unsupervised

  postgresql:
    parameters:
      shared_buffers: 256MB
      pg_stat_statements.max: '10000'
      pg_stat_statements.track: all
      auto_explain.log_min_duration: '10s'
      "pgaudit.log": "all, -misc"
      "pgaudit.log_catalog": "off"
      "pgaudit.log_parameter": "on"
      "pgaudit.log_relation": "on"
      "pgaudit.log_statement": none" 
      "pgaudit.log_min_messages": "error"
      "pgaudit.log_checkpoints": "on"
      "pgaudit.log_lock_waits": "on"
      "pgaudit.log_temp_files": "0"
      "pgaudit.log_connections": "on"
      "pgaudit.log_disconnections": "on"
      "pgaudit.log_hostname": "on"
    pg_hba:
      - host all all all md5


  bootstrap:
    recovery:
      source: cpho-postgres-restore
      owner: cpho-phase2_db_user
      database: cpho-phase2_db

  storage:
    storageClass: standard
    size: 1Gi

  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: false
  
  serviceAccountTemplate:
    metadata:
      annotations:
        # insert the service account token
        iam.gke.io/gcp-service-account: hopicpostgresbackup@phx-01h4rr1468rj3v5k60b1vserd3.iam.gserviceaccount.com	

  backup:
    barmanObjectStore:
      destinationPath: gs://hopic-dev-postgres-backup
      googleCredentials:
        gkeEnvironment: true
    retentionPolicy: "30d"	

  externalClusters:
    - name: cpho-postgres-restore
      barmanObjectStore:
        serverName: cpho-postgres-cluster
        destinationPath: gs://hopic-dev-postgres-backup/
        googleCredentials:
          gkeEnvironment: true
        wal:
          maxParallel: 8
