apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: server-django
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./k8s/server/overlays/ephemeral/django
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  # dependsOn:
  #   - name: server-postgres
  decryption:
    provider: sops
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: istio-version
