# Modified from https://cloud.google.com/python/django/run

# [START cloudrun_django_cloudbuild]
steps:
  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:${COMMIT_SHA}", "server/."]


  - id: "push image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:${COMMIT_SHA}"]

  # - id: "apply migrations"
  #   name: "gcr.io/google-appengine/exec-wrapper"
  #   args:
  #     [
  #       "-i",
  #       "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:${COMMIT_SHA}",
  #       "-s",
  #       "${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}",
  #       "-e",
  #       "SETTINGS_NAME=${_SECRET_SETTINGS_NAME}",
  #       "--",
  #       "python",
  #       "manage.py",
  #       "migrate",
  #     ]

  - id: "deploy to cloud run"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:${COMMIT_SHA}",
        "--region",
        "${_REGION}",
        "--add-cloudsql-instances",
        "${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}", 
        "--platform", 
        "managed",
        "--allow-unauthenticated",   
      ]

substitutions:
  _INSTANCE_NAME: cpho-db-instance
  _REGION: northamerica-northeast1
  _SERVICE_NAME: "cpho-phase2"
  _SECRET_SETTINGS_NAME: django_settings
  _ARTIFACT_REGISTRY_REPO: "cpho-artifact-registry-for-cloud-run"
  

images:
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:${COMMIT_SHA}"
  # - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}"

# [END cloudrun_django_cloudbuild]
