# Docker compose file for running tests.

version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes: 
      - db:/var/lib/postgresql/data
      - ./server/.env.dev-public:/docker-entrypoint-initdb.d/.env.dev-public
      - ./server/dev-db-init.sh:/docker-entrypoint-initdb.d/dev-db-init.sh
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust  

  server:
    build: ./server
    image: cpho-test-image
    user: root
    command: >
      sh -c "
      coverage run -m pytest &&
      coverage report --show-missing &&
      coverage json -o /cpho/web/coverage/coverage.json --pretty-print"
    env_file:
      - ./server/.env.dev-public
    environment:
    # NOTE: Given Compose environment variable precedence (https://docs.docker.com/compose/environment-variables/envvars-precedence/),
    #       the environment variable set here will ONLY override variables set in env_file because we're using decouple, and 
    #       decouple.Config looks in OS env vars before .env files. 
    #       If the behaviour changes, or if this is run without using decouple, setting DB_HOST=db here will no longer work. 
      - DB_HOST=db
    volumes:
      - ./coverage:/cpho/web/coverage 
    depends_on:
      - db

volumes:
  db:
    driver: local

networks:
  default:
    name: cloudbuild
    external: true
# NOTE:  An issue with error around network label being incorrect - fixed by: "docker network create --label com.docker.compose.network=cloudbuild cloudbuild"


