# Docker compose file for running tests in Cloud Build.
# Note: If testing locally, 
#       - Set IMAGE_NAME_FOR_RUN (export IMAGE_NAME_FOR_RUN=image_for_tests)
#       - Change the network to external: false.

version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./server/.env.dev
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  server:
    build: ./server
    image: ${IMAGE_NAME_FOR_RUN}
    command: >
      sh -c "
      exec gunicorn --bind 0.0.0.0:8080 --workers 1 --threads 8 --timeout 0 server.wsgi:application"
    env_file:
      - ./server/.env.dev
    environment:
      - DB_HOST=db
    depends_on:
      - db

volumes:
  db:
    driver: local

networks:
  default:
    name: cloudbuild
    # external: true
    external: false

