version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./server/.env.dev
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
 

  server:
    build: ./server
    image: ${IMAGE_NAME_FOR_RUN}
    # ${BUILD_CLOUD_RUN_IMAGE_NAME}:${COMMIT_SHA}
    # image: northamerica-northeast1-docker.pkg.dev/phx-01h4rr1468rj3v5k60b1vserd3/cpho-phase2-artifact-registry-for-cloud-run/cpho-phase2:${COMMIT_SHA}
    command: >
      sh -c "
      python ./manage.py migrate && \
      python ./manage.py loaddata cpho/fixtures/dimension_lookups.yaml && \
      python ./manage.py loaddata cpho/fixtures/periods.yaml && \
      python ./manage.py runscript cpho.scripts.dev && \
      exec gunicorn --bind 0.0.0.0:8080 --workers 1 --threads 8 --timeout 0 server.wsgi:application"
    ports:
      - 8080:8080
    env_file:
      - ./server/.env.dev
    environment:
      - DB_HOST=db
      - POSTGRES_HOST_AUTH_METHOD=trust 
    depends_on:
      - db

volumes:
  db:
    driver: local

networks:
  default:
    name: cloudbuild
    external: true
    # external: false

