# Docker compose file for running tests.

version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
      args:
        - DEPENDENCY_SET=test
    entrypoint: ["python", "./entrypoint.format.py"]
    env_file:
      - ./server/.env.dev-public
    volumes:
      # the pyproject.toml needs to be at the repo top level for VS Code plugins to pick it up,
      # but the repo top level isn't included in our container builds. The formatting scripts need
      # to read settings from it, so we mount it to the container at runtime when checking formatting
      - type: bind
        source: ./pyproject.toml # relative to the compose file, not the context dir
        target: /cpho/web/pyproject.toml
        read_only: true

networks:
  default:
    name: cloudbuild
    external: true
# NOTE:  An issue with error around network label being incorrect - fixed by: "docker network create --label com.docker.compose.network=cloudbuild cloudbuild"

