version: "3.8"
name: cpho
services:
  # proxies localhost:3000 to containers based on rules in envoy.yaml
  envoy:
    image: envoyproxy/envoy-distroless-dev
    entrypoint: envoy
    command: [ "-l", "warn", "-c", "/etc/envoy.yaml", "--service-cluster", "envoy"]
    volumes:
      - ./envoy.yaml:/etc/envoy.yaml # Envoy configuration
    expose:
      - "3000" # Forward to proxied apps
      - "3001" # Envoy admin page
    ports:
      - "3000:3000"
      - "3001:3001"
  postgres:
    image: postgres:alpine
    env_file: ./server/postgres.env
    ports:
      - 5432
    expose:
      - 5432
  migrations:
    build: ./server
    working_dir: /server
    env_file: ./server/server.env
    # restart: on-failure
    volumes:
    - type: bind
      source: ./server
      target: /server
    command: python manage.py migrate
    depends_on:
      - postgres
  server:
    build: ./server
    working_dir: /server
    env_file: ./server/server.env
    # restart: on-failure
    ports:
      - 8000
    expose:
      - 8000
    volumes:
    - type: bind
      source: ./server
      target: /server
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - migrations
  frontend:
    build: ./frontend
    ports:
      - 3000
    expose:
      - 3000
    command: npm start
    volumes:
      - type: bind
        source: ./frontend
        target: /frontend
    depends_on:
      - server
volumes:
  driver: {}
