# Docker compose file for running tests in Cloud Build.
# Note: If testing locally, 
#       - Set IMAGE_NAME_FOR_RUN (export IMAGE_NAME_FOR_RUN=image_for_tests)
#       - Change the network to external: false.

version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    ports:
      - "5432:5432" 
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./server/.env.dev:/docker-entrypoint-initdb.d/.env.dev
      # - ./server/dev-db-init.sh:/docker-entrypoint-initdb.d/dev-db-init.sh
    # environment:
    #   - POSTGRES_HOST_AUTH_METHOD=trust  

  server:
    build: ./server
    image: ${IMAGE_NAME_FOR_RUN}
    command: >
      sh -c "
      coverage run -m pytest &&
      coverage report --show-missing"
    env_file:
      - ./server/.env.dev
    environment:
    # NOTE: Given Compose environment variable precedence (https://docs.docker.com/compose/environment-variables/envvars-precedence/),
    #       the environment variable set here will ONLY override variables set in env_file because we're using decouple, and 
    #       decouple.Config looks in OS env vars before .env files. 
    #       If the behaviour changes, or if this is run without using decouple, this will no longer work. 
      - DB_HOST=db
    depends_on:
      - db

volumes:
  db:
    driver: local

networks:
  default:
    name: cloudbuild
    external: true
    # external: false

