version: "3.8"
services:
  postgres:
    image: postgres:alpine
    env_file: ./server/postgres.env
    network_mode: host
  migrations:
    build: ./server
    working_dir: /server
    env_file: ./server/server.env
    # restart: on-failure
    volumes:
    - type: bind
      source: ./server
      target: /server
    command: python manage.py migrate
    network_mode: host
    depends_on:
      - postgres
  server:
    build: ./server
    working_dir: /server
    env_file: ./server/server.env
    # restart: on-failure
    ports:
      - 8000:8000
    volumes:
    - type: bind
      source: ./server
      target: /server
    command: python manage.py runserver 0.0.0.0:8000
    network_mode: host
    depends_on:
      - migrations
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    command: npm start
    volumes:
      - type: bind
        source: ./frontend
        target: /frontend
    depends_on:
      - server
    network_mode: host
