---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg-system
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./k8s/cnpg-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  dependsOn:
    - cert-manager-resources
