apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: infra-sync
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: add-infra-sync
  secretRef:
    name: flux-system
  url: ssh://git@github.com/PHACDataHub/cpho-phase2
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./infrastructure
  prune: false
  sourceRef:
    kind: GitRepository
    name: infra-sync
  decryption:
    provider: sops
