version: 2
updates:
# Dockerfile
- package-ecosystem: docker
  directory: "/server"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 5

# cloudbuild.yaml
 - package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"

# requirements*.txt
- package-ecosystem: pip
  directory: "/server"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 5
 






  








  











