apiVersion: v1
data:
    token: ENC[AES256_GCM,data:U559DdBQSDZB034y6EikKNNCHsdDGFRPfWkaIX+6MHPvQPxOjVEZdweEJZ72UH8E14kwmaKUUunckWLFEzqvPpZttwjMy5RRKJ3qFb2gJfITJ2vVb2s4B+jAJruiL/YEsclOPIwe2rBCdXF/Dp0X6m8E463BK7ZYKzfv7w==,iv:qZfbAh1ZUVXsIIInKtoQB8+HSUFkNLyF8rXzc1GJRL0=,tag:c/NLwx9Y/txyi1BKMs9Rsg==,type:str]
kind: Secret
metadata:
    name: github-status-token
    namespace: demo
type: Opaque
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/phx-01h4rr1468rj3v5k60b1vserd3/locations/northamerica-northeast1/keyRings/sops/cryptoKeys/sops-key
          created_at: "2023-12-12T18:51:17Z"
          enc: CiQABjWkUDES/odHuNLacSsWGXm1v02LYspEGij6Ns76mSuLvvUSSQB/rzHLqdSgH2Amj73WMuEorMj+n5ufavQigkCK0SRhssoNvcsGJVVtHi+7hjcLhGi0fVfCTJRaXBZtyMhQ6hHRHGW7dVbAKgM=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-12T18:51:18Z"
    mac: ENC[AES256_GCM,data:6+SkX0uZ+qBExsBGrlC/VOQIYcSFZcmrn3BrhpLWOGVP6IWtvkLomvXIQfIfGDMErepmxRhfeFa+4AlMdZ8Ev/cO3BHg15A2Gd2sUZVzLseE0t5kwgzMb+Awr8A4uTLyi3reWDomIF4VUl1tRA4qtU1A8FqNGtmIdi9SFubOGGE=,iv:2nSzXiCtlj0OWQcco4DH1vbNBdMSA8+jM6S4eUxcEoE=,tag:P1EiNVfs1Qu/TP70ttGZrw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
data:
    token: ENC[AES256_GCM,data:3Oun9hCDS6on5xeRDmNc035izwLDb1wC27KjhXEwffgPKwXW3lxTXcNCwQ8h8DVEUOnkYniKyZ7Kb1a57cHsYTGI/mYeBHLyJzmpVA==,iv:ZVb9dwsLfRVu4heI/K32j2pUNhuR5sNXbOB3ExCIJ7M=,tag:by3AET62CL8DBOFJRmR37A==,type:str]
kind: Secret
metadata:
    name: slack-bot-token
    namespace: demo
type: Opaque
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/phx-01h4rr1468rj3v5k60b1vserd3/locations/northamerica-northeast1/keyRings/sops/cryptoKeys/sops-key
          created_at: "2023-12-12T18:51:17Z"
          enc: CiQABjWkUDES/odHuNLacSsWGXm1v02LYspEGij6Ns76mSuLvvUSSQB/rzHLqdSgH2Amj73WMuEorMj+n5ufavQigkCK0SRhssoNvcsGJVVtHi+7hjcLhGi0fVfCTJRaXBZtyMhQ6hHRHGW7dVbAKgM=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-12T18:51:18Z"
    mac: ENC[AES256_GCM,data:6+SkX0uZ+qBExsBGrlC/VOQIYcSFZcmrn3BrhpLWOGVP6IWtvkLomvXIQfIfGDMErepmxRhfeFa+4AlMdZ8Ev/cO3BHg15A2Gd2sUZVzLseE0t5kwgzMb+Awr8A4uTLyi3reWDomIF4VUl1tRA4qtU1A8FqNGtmIdi9SFubOGGE=,iv:2nSzXiCtlj0OWQcco4DH1vbNBdMSA8+jM6S4eUxcEoE=,tag:P1EiNVfs1Qu/TP70ttGZrw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
