apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: demo
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: "configure-sops"
  secretRef:
    name: flux-system
  url: ssh://git@github.com/PHACDataHub/cpho-phase2
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: demo
  namespace: demo
spec:
  interval: 2m0s
  path: ./k8s/demo
  prune: true
  sourceRef:
    kind: GitRepository
    name: demo
  wait: true
