from django.urls import path, re_path

from . import views

urlpatterns = [
    path("manage_users/", views.ManageUsers.as_view(), name="manage_users"),
    path(
        "manage_users/create/", views.CreateUser.as_view(), name="create_user"
    ),
    path(
        "users/<int:user_id>/edit/",
        views.ModifyUser.as_view(),
        name="modify_user",
    ),
    path(
        "indicators/", views.ListIndicators.as_view(), name="list_indicators"
    ),
    path(
        "indicators/<int:pk>/",
        views.ViewIndicator.as_view(),
        name="view_indicator",
    ),
    path(
        "indicators/<int:pk>/<int:period_pk>/",
        views.ViewIndicatorForPeriod.as_view(),
        name="view_indicator_for_period",
    ),
    path(
        "indicators/<int:pk>/edit/",
        views.EditIndicator.as_view(),
        name="edit_indicator",
    ),
    path(
        "indicators/create/",
        views.CreateIndicator.as_view(),
        name="create_indicator",
    ),
    path(
        "indicators/upload/",
        views.UploadIndicator.as_view(),
        name="upload_indicator",
    ),
    path(
        "indicators/upload/preview/",
        views.PreviewUpload.as_view(),
        name="preview_upload",
    ),
    path(
        "indicators/upload/save/",
        views.SaveUpload.as_view(),
        name="save_upload",
    ),
    path(
        "indicators/<int:indicator_id>/period/<int:period_pk>/manage_data/<int:dimension_type_id>/",
        views.ManageIndicatorData.as_view(),
        name="manage_indicator_data",
    ),
    path(
        "indicators/<int:indicator_id>/period/<int:period_pk>/manage_data/all/",
        views.ManageIndicatorData.as_view(),
        name="manage_indicator_data_all",
    ),
    path(
        "indicators/<int:indicator_id>/period/<int:period_pk>/submit_data/<int:dimension_type_id>/",
        views.SubmitIndicatorData.as_view(),
        name="submit_indicator_data",
    ),
    path(
        "indicators/<int:indicator_id>/period/<int:period_pk>/submit_data/all/",
        views.SubmitIndicatorData.as_view(),
        name="submit_indicator_data_all",
    ),
    path(
        "indicators/<int:indicator_id>/period/<int:period_pk>/review_data/<int:dimension_type_id>/",
        views.ReviewData.as_view(),
        name="review_indicator_data",
    ),
    path(
        "indicators/<int:indicator_id>/period/<int:period_pk>/review_data/all/",
        views.ReviewData.as_view(),
        name="review_indicator_data_all",
    ),
    path(
        "indicators/<int:indicator_id>/changelog/",
        views.IndicatorScopedChangelog.as_view(),
        name="indicator_scoped_changelog",
    ),
    path(
        "indicators/<int:indicator_id>/changelog/<int:page_num>/",
        views.IndicatorScopedChangelog.as_view(),
        name="indicator_scoped_changelog",
    ),
    path(
        "users/<int:user_id>/changelog/",
        views.UserScopedChangelog.as_view(),
        name="user_scoped_changelog",
    ),
    path(
        "users/<int:user_id>/changelog/<int:page_num>/",
        views.UserScopedChangelog.as_view(),
        name="user_scoped_changelog",
    ),
    path(
        "global-changelog/",
        views.GlobalChangelog.as_view(),
        name="global_changelog",
    ),
    path(
        "global-changelog/<int:page_num>/",
        views.GlobalChangelog.as_view(),
        name="global_changelog",
    ),
    path(
        "indicators/<int:pk>/export/",
        views.ExportIndicator.as_view(),
        name="export_indicator",
    ),
    path(
        "indicators/export/template/",
        views.ExportIndicator.as_view(),
        name="export_indicator_template",
    ),
    path(
        "indicators/<int:indicator_id>/benchmarking/",
        views.ManageBenchmarkingData.as_view(),
        name="manage_benchmarking_data",
    ),
    path(
        "indicators/<int:indicator_id>/trend_analysis/",
        views.ManageTrendAnalysisData.as_view(),
        name="manage_trend_analysis_data",
    ),
]
