apiVersion: v1
kind: ConfigMap
metadata:
  name: server
data:
  IS_K8S: "true"
  ALLOWED_HOSTS: "hopic-sdpac.data-donnes.phac-aspc.gc.ca,34.149.100.163,localhost,34.152.0.41,41.0.152.34.bc.googleusercontent.com"
  DB_NAME: "cpho-phase2_db"
  DB_HOST: "cpho-postgres14-cluster-rw"
  DB_PORT: "5432"
  PHAC_ASPC_OAUTH_PROVIDER: "microsoft"
  PHAC_ASPC_SESSION_COOKIE_AGE: "259200"
