apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  template:
    spec:
      containers:
      - name: server
        image: northamerica-northeast1-docker.pkg.dev/pht-01hp04dtnkf/hopic-k8s-images/cpho-phase2:prod-0b50c515-1724341604 # {"$imagepolicy": "flux-system:server"}
        resources:
          # Autopilot only considers requests (see https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-resource-requests#resource-limits)
          requests:
            cpu: 100m
            memory: 1Gi
        envFrom:
        - configMapRef:
            name: server
