apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: server
spec:
  maxReplicas: 8
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: server
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        # memory usage is high due to multiple active gunicorn workers, but tends to remains stable under load,
        # so a higher average utilization target for scaling is preferable
        averageUtilization: 85
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 65
