apiVersion: v1
data:
    secret-key: ENC[AES256_GCM,data:b8L0VW+gOHddobbQs1/w4FLN8sY1VByNtnURWv59koeN2EpMHa5981UMU3A03wkMZimskyURZND/2r35tpcflGUQLUdfkVtn,iv:wt8UMusLe5PyFoDgSG28oNFq7l6cLIafE8/Wr09oyFk=,tag:sw+PI/jxJ+jktwvMkoB3jQ==,type:str]
kind: Secret
metadata:
    name: django-secret-key
type: Opaque
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/pht-01hp04dtnkf/locations/northamerica-northeast1/keyRings/sops/cryptoKeys/sops-flux-key
          created_at: "2024-02-08T13:33:46Z"
          enc: CiQA5+PIYjf21HETzAuNArBQq3w0zqeuHki4yWgYbu8OPUVlQ80SSAD25I1PiU1mX6HIE1CiVEts57EArGPUwn08bzf30s2Z0/ynnn7wb1eNG7DZMJvFsgfQcaXn8GbiMQ+++Hq+Dnr77jK+d1PAAw==
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-02-08T13:33:46Z"
    mac: ENC[AES256_GCM,data:tan9J7/dBC15Y0OL6zvKn/UcOdi9BuZmmcED6MV+AWzK3jXR2v7GgfPDATCw6cAcpZDOtzA9rNDZYgdFgQ6ljrZ2R8KVmTTRjoFA9Co8ZEBCg6+BMsNQe+T2UD7Pi3ISZ5+zHNvQFAdVdOe8IxZu2uIPIzsi6ajUyLTnxDuDGgk=,iv:DyRRJW66s84h68Ob8D/Giu7r584rdCPKC15CKKsGDOs=,tag:Cw+D9ATxwdWK4/GFiGQ1GA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
data:
    client-id: ENC[AES256_GCM,data:d9mQVi0OWhdK6UqNjLHrL5i9bjF2WC4uZPnXQSStamQcqM85QaJlNebAfPUIJZVf,iv:5tnkJcZeP+qTAZwfU12SRBVOQLYHd1Mb/9hJSUs701E=,tag:WwCxKMLVhnT1w7TG8/Absw==,type:str]
    client-secret: ENC[AES256_GCM,data:yvFQafnJuehtKS0ZvIB8ajOkfs+QOdeiSWm7OHsDCvhc76Q3phvLYFuDolTFl3iD+BHLaRMsPPE=,iv:iHDWIH5G40hPoDk9T3aP7Cw5ATuMBEAKLu76YS6a4cc=,tag:neN/oz8JmshUnilkKqw7Og==,type:str]
    microsoft-tenant: ENC[AES256_GCM,data:6UXw7e7VX3GwvQGylohqM9RJVIvGfkCwAKzuuwKxg08d9v+HTgsuV4GnnHThzCJ7,iv:aMfbyZ5ATiacXBB+ER1t+RrePYCjV1J5JLVf6v/SNpU=,tag:M23y5YC4ze3vah2VBVj2wg==,type:str]
kind: Secret
metadata:
    name: phac-aspc-oauth-config
type: Opaque
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/pht-01hp04dtnkf/locations/northamerica-northeast1/keyRings/sops/cryptoKeys/sops-flux-key
          created_at: "2024-02-08T13:33:46Z"
          enc: CiQA5+PIYjf21HETzAuNArBQq3w0zqeuHki4yWgYbu8OPUVlQ80SSAD25I1PiU1mX6HIE1CiVEts57EArGPUwn08bzf30s2Z0/ynnn7wb1eNG7DZMJvFsgfQcaXn8GbiMQ+++Hq+Dnr77jK+d1PAAw==
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-02-08T13:33:46Z"
    mac: ENC[AES256_GCM,data:tan9J7/dBC15Y0OL6zvKn/UcOdi9BuZmmcED6MV+AWzK3jXR2v7GgfPDATCw6cAcpZDOtzA9rNDZYgdFgQ6ljrZ2R8KVmTTRjoFA9Co8ZEBCg6+BMsNQe+T2UD7Pi3ISZ5+zHNvQFAdVdOe8IxZu2uIPIzsi6ajUyLTnxDuDGgk=,iv:DyRRJW66s84h68Ob8D/Giu7r584rdCPKC15CKKsGDOs=,tag:Cw+D9ATxwdWK4/GFiGQ1GA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
data:
    token: ENC[AES256_GCM,data:f74U+CA9Cao1/5EABTuPt51CFM8iE1T/bVnhx4jtcGzNayFn/3p3wftr5AEzk3M8+QJf+TcP4U7MS8gUIgclJIGXZDFjpVL+3/a4Jw==,iv:UHwfSUQwqRP6jtT38TdT8yq3IrhAq++kixkwBWdYnIo=,tag:Ulb2Forb0UVIoEC+I3f4pg==,type:str]
kind: Secret
metadata:
    name: slack-alerting-app-token
type: Opaque
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/pht-01hp04dtnkf/locations/northamerica-northeast1/keyRings/sops/cryptoKeys/sops-flux-key
          created_at: "2024-02-08T13:33:46Z"
          enc: CiQA5+PIYjf21HETzAuNArBQq3w0zqeuHki4yWgYbu8OPUVlQ80SSAD25I1PiU1mX6HIE1CiVEts57EArGPUwn08bzf30s2Z0/ynnn7wb1eNG7DZMJvFsgfQcaXn8GbiMQ+++Hq+Dnr77jK+d1PAAw==
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-02-08T13:33:46Z"
    mac: ENC[AES256_GCM,data:tan9J7/dBC15Y0OL6zvKn/UcOdi9BuZmmcED6MV+AWzK3jXR2v7GgfPDATCw6cAcpZDOtzA9rNDZYgdFgQ6ljrZ2R8KVmTTRjoFA9Co8ZEBCg6+BMsNQe+T2UD7Pi3ISZ5+zHNvQFAdVdOe8IxZu2uIPIzsi6ajUyLTnxDuDGgk=,iv:DyRRJW66s84h68Ob8D/Giu7r584rdCPKC15CKKsGDOs=,tag:Cw+D9ATxwdWK4/GFiGQ1GA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
data:
    slack-url: ENC[AES256_GCM,data:m9IxT0wjhEkObhkkwTxHin7qS5w5LFjk+EIMcc9CdgVRsKiHx8VJvUTvGA2GMSN1xpRHcaog8jH7OArEGU/s+WsjmfTt8RKXU5YBqAL0oPoorHW6XFk5wG9Q1EMyGeMh1Nk/+4GVfQfaXUx2,iv:bQxwAvYh4NDRndEtyetolvDNRPWrruAXDAcbCiRStxQ=,tag:wxFPpDkIQlCsEjm3Xgp+KQ==,type:str]
kind: Secret
metadata:
    name: slack-webhook-url
type: Opaque
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/pht-01hp04dtnkf/locations/northamerica-northeast1/keyRings/sops/cryptoKeys/sops-flux-key
          created_at: "2024-02-08T13:33:46Z"
          enc: CiQA5+PIYjf21HETzAuNArBQq3w0zqeuHki4yWgYbu8OPUVlQ80SSAD25I1PiU1mX6HIE1CiVEts57EArGPUwn08bzf30s2Z0/ynnn7wb1eNG7DZMJvFsgfQcaXn8GbiMQ+++Hq+Dnr77jK+d1PAAw==
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-02-08T13:33:46Z"
    mac: ENC[AES256_GCM,data:tan9J7/dBC15Y0OL6zvKn/UcOdi9BuZmmcED6MV+AWzK3jXR2v7GgfPDATCw6cAcpZDOtzA9rNDZYgdFgQ6ljrZ2R8KVmTTRjoFA9Co8ZEBCg6+BMsNQe+T2UD7Pi3ISZ5+zHNvQFAdVdOe8IxZu2uIPIzsi6ajUyLTnxDuDGgk=,iv:DyRRJW66s84h68Ob8D/Giu7r584rdCPKC15CKKsGDOs=,tag:Cw+D9ATxwdWK4/GFiGQ1GA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
