# Generated by Django 4.0.6 on 2022-07-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatordata',
            name='value_lower_bound',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='indicatordata',
            name='value_upper_bound',
            field=models.FloatField(null=True),
        ),
    ]
