# Generated by Django 4.0.6 on 2022-07-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_indicatordata_value_lower_bound_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatordata',
            name='age_group',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='indicatordata',
            name='age_group_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='indicatordata',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='indicatordata',
            name='multi_year_timeframe',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='indicatordata',
            name='sex',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='indicatordata',
            name='single_year_timeframe',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
