---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: server-postgres
  namespace: flux-system
spec:
  path: ./k8s/server/overlays/prod/postgres
  interval: 2m0s
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  dependsOn:
    - name: cnpg-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: server-postgres-backup
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./k8s/server/overlays/prod/postgres/backup
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: server-postgres
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: server-django
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./k8s/server/overlays/prod/django
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: server-postgres
  decryption:
    provider: sops
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: server
  namespace: flux-system
spec:
  image: northamerica-northeast1-docker.pkg.dev/pht-01hp04dtnkf/hopic-k8s-images/cpho-phase2
  interval: 1m0s
  provider: gcp
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: server
  namespace: flux-system
spec:
  filterTags:
    extract: $ts
    pattern: ^prod-[a-fA-F0-9]+-(?P<ts>.*)
  imageRepositoryRef:
    name: server
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: cpho-updater
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 5m
  update:
    strategy: Setters
    path: .
  git:
    checkout:
      ref:
        branch: "prod"
    commit:
      author:
        name: fluxbot
        email: fluxcd@users.noreply.github.com
      messageTemplate: "[ci skip] {{range .Updated.Images}}{{println .}}{{end}}"
    push:
      branch: "prod"
