#  ___| | __ _  ___| | __
# / __| |/ _` |/ __| |/ /
# \__ \ | (_| | (__|   <
# |___/_|\__,_|\___|_|\_\
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: slack-bot
  namespace: flux-system
spec:
  type: slack
  channel: cpho-hopic-prod-alerts
  address: https://slack.com/api/chat.postMessage
  secretRef:
    name: slack-bot-token
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: slack
  namespace: flux-system
spec:
  summary: "Notifications for flux reconciliations"
  eventMetadata:
    cluster: "gke_pht-01hp04dtnkf_northamerica-northeast1_hopic"
    region: "northamerica-northeast1"
  providerRef:
    name: slack-bot
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
    - kind: ImageUpdateAutomation
      name: '*'
  exclusionList:
    # Due to the dependencies specified between resources, sometimes during reconciliations 
    # the resources go into a `dependency is not ready` state and Flux immediately starts 
    # complaining about it. This filter ignores any depedency related alerts given the fact 
    # that they will be reconciled eventually and eny error during reconciliations will be 
    # reported separately.
    - "^Dependencies.*"
    # Following addition is more of a "band-aid" solution to spammy `Namespace/cnrm-system configured`
    # messages until an actual solution is figured out. This only ignores alerts for cnrm-system's
    # namespace which, like any other namespace config, is hardly expected to change.
    - "Namespace/cnrm-system configured"
---
#        _ _   _           _
#   __ _(_) |_| |__  _   _| |__
#  / _` | | __| '_ \| | | | '_ \
# | (_| | | |_| | | | |_| | |_) |
#  \__, |_|\__|_| |_|\__,_|_.__/
#  |___/
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: github-status
  namespace: flux-system
spec:
  type: github
  address: https://github.com/PHACDataHub/cpho-phase2
  secretRef:
    name: github-status-token
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: github-status
  namespace: flux-system
spec:
  providerRef:
    name: github-status
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: '*'
  exclusionList:
    - "^Dependencies.*"
---
