apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  template:
    spec:
      containers:
      - name: server
        image: northamerica-northeast1-docker.pkg.dev/pht-01hp04dtnkf/hopic-k8s-images/cpho-phase2:prod-2484c95c-1721144758 # {"$imagepolicy": "flux-system:server"}
        resources:
          # Autopilot only considers requests (see https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-resource-requests#resource-limits)
          requests:
            # Experiment: using the minimum pod resources https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-resource-requests#compute-class-min-max
            cpu: 200m # + `isito-proxy` container = 250m
            memory: 500Mi # + `isito-proxy` container = 512MiB
        envFrom:
        - configMapRef:
            name: server
        readinessProbe:
          httpGet:
            httpHeaders:
            - name: Host
              value: ${BRANCH_NAME}.dev.hopic-sdpac.data.phac.gc.ca
