apiVersion: v1
data:
    secret-key: ENC[AES256_GCM,data:2h45Kr/tLNFzKcDs+AYOn1a4vxsZSiYXC+PD4b+dR0aCZiN/gne9dBzKqlKszEcWpbHf26gNA8ujExNCvKk8vMPD4mEeV1LT,iv:n2br1SaBbW0CmscKEMl+76o821TTKFJ5D8UwIsaVJlE=,tag:J4nAvNxE+PmGynuCLe2J7A==,type:str]
kind: Secret
metadata:
    name: django-secret-key
type: Opaque
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/pht-01hp04dtnkf/locations/northamerica-northeast1/keyRings/sops/cryptoKeys/sops-flux-key
          created_at: "2024-04-22T11:50:00Z"
          enc: CiQA5+PIYh6aXG4RYhAdwvLsr+rh1906ud6ZovQcPrkvnpzCZdUSSQDc6DxTujMzn3MV2xb+iYDzL3uaNmwIYv3LrqKVsvr6mHAvuKjwkSykvqivS4Gp7SVk4apwUIlgUP9ZFUNd8IDNwCVk9zxQoHk=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-04-22T11:50:00Z"
    mac: ENC[AES256_GCM,data:UAsIUPlQSf7vWSYtKtN7LEzj5n7zf3uRqBpl9dAMoQNbxS02gOdc92vtzIi8Wb6Bl57MCHT7F2Vb2N3vZolA+iI5xwfwj92nmlMrfTfue7rEM4mLO0xzwgsd2Tzxeu65RONqpc5W0LEkBjTdzPd59P2Mrv045Q8meVYxDpRVwf4=,iv:f900Ux8Z4wv+KlZSXy+nzCGcKi1W1Ie2Q6WnzC5xuh8=,tag:LLVcZNwVuZMByaSXHvpUuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
data:
    client-id: ENC[AES256_GCM,data:Pr69J1m3gTHL2E+fr0BYZCSASzv9MUZGIy0ULHq+IGIw7JRcR3uOCSV5D0qMPuaQ,iv:EnFgqDG9y0qK9E54kEc1GyJ058kQ3PbxeRlLJetpF7I=,tag:yHnfulMzqp9WyauAf4iDpQ==,type:str]
    client-secret: ENC[AES256_GCM,data:YuUgKm9WAYXwXMupx0/M3caSlJlTl5wiOXduUNJVsMNWF89G5/Ct9XiNRgjUJ6aCZSK2we0tObg=,iv:LtjIPN7tgOJk8R7m1Q87qgsacG7TCBvG4h9zYYg4M4k=,tag:mAozSWzjsYVr/L2UvySieQ==,type:str]
    microsoft-tenant: ENC[AES256_GCM,data:63RQ7PgNYP8gkHZsz3fIEnEEzrMIHljgAFyczOjY3oNSn7vQ8kZx+AxdDtNSTNIf,iv:OiWRNOUt/nCQ2xJxqxZ9ck3wM496S4lwDgdQ/WJDfO8=,tag:7ygWDJNGnwPBn8j2PxIK3w==,type:str]
kind: Secret
metadata:
    name: phac-aspc-oauth-config
type: Opaque
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/pht-01hp04dtnkf/locations/northamerica-northeast1/keyRings/sops/cryptoKeys/sops-flux-key
          created_at: "2024-04-22T11:50:00Z"
          enc: CiQA5+PIYh6aXG4RYhAdwvLsr+rh1906ud6ZovQcPrkvnpzCZdUSSQDc6DxTujMzn3MV2xb+iYDzL3uaNmwIYv3LrqKVsvr6mHAvuKjwkSykvqivS4Gp7SVk4apwUIlgUP9ZFUNd8IDNwCVk9zxQoHk=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-04-22T11:50:00Z"
    mac: ENC[AES256_GCM,data:UAsIUPlQSf7vWSYtKtN7LEzj5n7zf3uRqBpl9dAMoQNbxS02gOdc92vtzIi8Wb6Bl57MCHT7F2Vb2N3vZolA+iI5xwfwj92nmlMrfTfue7rEM4mLO0xzwgsd2Tzxeu65RONqpc5W0LEkBjTdzPd59P2Mrv045Q8meVYxDpRVwf4=,iv:f900Ux8Z4wv+KlZSXy+nzCGcKi1W1Ie2Q6WnzC5xuh8=,tag:LLVcZNwVuZMByaSXHvpUuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
data:
    token: ENC[AES256_GCM,data:IlJrvZg/ahGSlT+dQA7r0zEJ6yxb9fiIM96j6Sj+X1yKa1Se6hIr4cVBkiD160g5H1fzwxjS/Jw93KfddbdVOf2oUBU9M4Bw/k25ug==,iv:yL0NweTT+/2608WVuDdzP2boFGUbtSBVjBawsdWH5rM=,tag:qNNz+GvaS2fCAPUrO+CQTg==,type:str]
kind: Secret
metadata:
    name: slack-alerting-app-token
type: Opaque
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/pht-01hp04dtnkf/locations/northamerica-northeast1/keyRings/sops/cryptoKeys/sops-flux-key
          created_at: "2024-04-22T11:50:00Z"
          enc: CiQA5+PIYh6aXG4RYhAdwvLsr+rh1906ud6ZovQcPrkvnpzCZdUSSQDc6DxTujMzn3MV2xb+iYDzL3uaNmwIYv3LrqKVsvr6mHAvuKjwkSykvqivS4Gp7SVk4apwUIlgUP9ZFUNd8IDNwCVk9zxQoHk=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-04-22T11:50:00Z"
    mac: ENC[AES256_GCM,data:UAsIUPlQSf7vWSYtKtN7LEzj5n7zf3uRqBpl9dAMoQNbxS02gOdc92vtzIi8Wb6Bl57MCHT7F2Vb2N3vZolA+iI5xwfwj92nmlMrfTfue7rEM4mLO0xzwgsd2Tzxeu65RONqpc5W0LEkBjTdzPd59P2Mrv045Q8meVYxDpRVwf4=,iv:f900Ux8Z4wv+KlZSXy+nzCGcKi1W1Ie2Q6WnzC5xuh8=,tag:LLVcZNwVuZMByaSXHvpUuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
data:
    slack-url: ENC[AES256_GCM,data:Te98cH5VcQuWdkGgJ4Ema1mOsE18uDa8pV/dkYGkSbhmbjkMTFWWXJaZzS/ghbY7EIeJAD/zRRFeEH3lCqCg7Bt6IP8VxK6JDfx6kwwr68U4f0K1JKgx0XS9sns+Pw6iu1rWNU4gC1L5b1IH,iv:/owYbqvVt/QNo/jvmVNBk6CNGWX3QEc+/2KVSOU8m0A=,tag:WkclYVWe8erCQDETJepJUA==,type:str]
kind: Secret
metadata:
    name: slack-webhook-url
type: Opaque
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/pht-01hp04dtnkf/locations/northamerica-northeast1/keyRings/sops/cryptoKeys/sops-flux-key
          created_at: "2024-04-22T11:50:00Z"
          enc: CiQA5+PIYh6aXG4RYhAdwvLsr+rh1906ud6ZovQcPrkvnpzCZdUSSQDc6DxTujMzn3MV2xb+iYDzL3uaNmwIYv3LrqKVsvr6mHAvuKjwkSykvqivS4Gp7SVk4apwUIlgUP9ZFUNd8IDNwCVk9zxQoHk=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-04-22T11:50:00Z"
    mac: ENC[AES256_GCM,data:UAsIUPlQSf7vWSYtKtN7LEzj5n7zf3uRqBpl9dAMoQNbxS02gOdc92vtzIi8Wb6Bl57MCHT7F2Vb2N3vZolA+iI5xwfwj92nmlMrfTfue7rEM4mLO0xzwgsd2Tzxeu65RONqpc5W0LEkBjTdzPd59P2Mrv045Q8meVYxDpRVwf4=,iv:f900Ux8Z4wv+KlZSXy+nzCGcKi1W1Ie2Q6WnzC5xuh8=,tag:LLVcZNwVuZMByaSXHvpUuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
