apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: server-virtual-service
spec:
  hosts:
    - ${BRANCH_NAME}.dev.hopic-sdpac.data.phac.gc.ca
  gateways:
  - istio-ingress/mesh-gateway
  http:
  - name: gateway-to-server
    match:
    - uri:
        prefix: /
    route:
    - destination:
        host: server.${BRANCH_NAME}.svc.cluster.local
