# Ref: https://cloud.google.com/config-connector/docs/how-to/install-namespaced#configure_to_run_in_namespaced_mode
apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnector
metadata:
  # the name is restricted to ensure that there is only one 
  # ConfigConnector resource installed in your cluster
  name: configconnector.core.cnrm.cloud.google.com
spec:
 mode: namespaced
