apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: istio-ingress
spec:
  commonName: hopic-sdpac.k8s.phac-aspc.alpha.canada.ca
  dnsNames:
    - hopic-sdpac.k8s.phac-aspc.alpha.canada.ca
  issuerRef:
    kind: Issuer
    # name: letsencrypt-staging
    name: letsencrypt
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 4096
  secretName: tlskeys
status: {}
