# Letsencrypt Production
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  # (Optional) Metadata
  # namespace: your-namespace
  namespace: istio-system
spec:
  acme:
    solvers: []
    preferredChain: ""
    # Letsencrypt Production
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory