---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certmanager
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./k8s/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m0s
