apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-alerting-app-token
  namespace: server
spec:
  encryptedData:
    token: AgBXLkxIEYgvfLfD9R3K2p9zPLE5VnICbIhp9NW1YM+JebyEPFQjburMo6NKv9Lrc1PCpT0cXvM0HukgOt1mu5P8dWo4aRHcT+g+ED/1hMAungIM308EQUR8xtk974m9FHGecVHeitkB/KKXtSRtBok7Kn1Gi33ad4+YTie5qbrhz7a9Qr+y351nlGPUyysrNv7dbfCTI2MkMTzurXQyuTnmZAJHfK2LM8EmWyQ8jNe1nbtOsdy/geLAngSCZ5n2pVXg8mdAHx/5eXTFO+0AV+g37fgGSoYHTsrdyMWcAeIpc5OtXaL71AdKLBcVNPzZEsN3NLfMYb2LMCG0dmRXAlQyaADEJ+5eo6JN/RICyfDNZS+oXwsiXzGmTknH3BkmEf5le6ajsDmVMhh4Be8M/BowLRuuAhgOsWTa+7DJnTBTaqHbFckY9SmsbBuitw1EaYBdgZzumum1spN3010h9Kh0bDUZ1qH0nsgN9TZubHA8z2vWZ6ykDbngnvgnralita6rhUWivWeRWy+TOdMed4NWWd5/nUZlHQD+U8XInxyiLB5YZLMi73k4d1U70X1AreJvVUzYHrkliJSxmYVFiAK+mKtPKrqmoApbeKEJOkqez9C5aESyDQHah31MbMHa5/Z0PULsU87BLlAT17NF+paLQir4seOH/WmiaMKOSaueH9yWRZIkZJPrtzdgJ+ZkzBj80vLrQpp0LAcCLE8ROB2+ZQsMm5HUDkDcLxmwEBmHAKYkHxx3pf66x+rePIShL8eA4Z9R5aFx0A==
  template:
    metadata:
      creationTimestamp: null
      name: slack-alerting-app-token
      namespace: server
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: django-secret-key
  namespace: server
spec:
  encryptedData:
    secret-key: AgBlkhtbHjV31R8NMwMY2714LEaZOYqSOXaJ4HqdGh5nVtfAUTB7zSlxo9KMQTmYoJN19zlsDuib8hpLwpN4k2GorqKIlH+SmQlpuiy8ObfUdTETVzqVADe79ejYsDPbJSSDpKUDMb5dJ3FhhC/oDbGUnK7KKZBVcjECW0MQnf+ghAUkBEHVaIxBuvmt3Np3gwVE4huh1ZQXVY4ReQW5wFrZtKjgCzPAY+FRd+AughnuUWN0mk9Fojzk9F+JEJzyJnXG2ELLV5VMSEGq5aGaVDJ+dZOkV90mY0wkhqdmO7UMdL6z8V9wBNW+ReajbQ5OzyvtE4BxpCR8elvVJ8qg5NyJRmO0Opf3E9Q5QAy9kRnPtdfAclz1wCtCoUv962JXe8ryS46CNXLD3skC8EoZrC/eUapyg0wHoUBWj4w5tcvgtNeDpgmvel0qw6aE1iovDpGeQqqXsOoCKv6C8Ajz7omSXbSjQu3guHd31B6uVk83ZBeNo6fCNbKdRzKIqdSj/s60Ht2k91JdrZsWx7yIrIxzh0n7WA6JyCNSOcWv6oKNHMubHlSTL7U7sSvmas9D/oAxQZ35JlVjDJ3iMfbnO6unqHbtvmHYfSeBU6LzsNOxW5WTwfXB4lAaJk276TvMZyBvNxe/UlOY9bec33IzYzZeU/SNzJXMFWih8Jy5Tc2f+SOGU0YpoJcsRiRRRi1DmJnRNBi07zLu7WEGg7XySn/J5okfSWQeFGs7493Uk2S3FBN89pWXKMcVlchuxvCVGtCRJbNWN0c=
  template:
    metadata:
      creationTimestamp: null
      name: django-secret-key
      namespace: server
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-webhook-url
  namespace: server
spec:
  encryptedData:
    slack-url: AgCeeluEPmiFL46ZrW/LvtgN5eLfA83odK/4DRxUTcgyG4d45B33zWCtpbKHoZieVfUU2HDD8M/DTd3IcLDJ1ElXxr/AhpxLFuwIjsEgnTXEFys8amBbGMm8rmcr2E/OWaEugo6uaE3PfTRlk8ykXWHxcbRRYyuPGXLlPshw/CNdb7HMkCBnjqR4KVQG0E3w4/FfbEUouSabBIRMluvzyyPSmfj4ZosLrejFJsP4pCAxNw02R6ylqvPOT/OMB9Fb0oA3msg4sBqHGbbvhZZ2Daos1Bt3NZiipry4E4yStSbqORFY3hNxt+xfPLSRPe2it9HyaD4k6kATqudQy3DWF/FFrRY7GsO/ybnPWli8VJYGagFqbm/N0kwkM3vYzrc4JEN26D16/3O3Avzr+gUtb2P+4ZyLVLB4iGgHVrVABiXGcypDOG8QpbwBjtqOF4F+yl3764nBhJaLgzX44uVvRpqid0Rev6eaxBLFdJLuXBybedQiew4zXj+FEU9pfA3P7RH4BWTCleI+C+NtSoZyIYd8q0+mfC2DMoWEbNzoe28fPZCaRkGRfeuYnpPeYQJpj+FNqB0MaUQsEYfZIhyE+UJ2aSCB+bfCK7b9KYGqK2i1eEw6KesQlliYB70edKX5ViWLRni6+zk5QA9XXIkvUPRKl4XoQCP4SXofq/dUu+AfPXZwOHraIBLoSxd/7Sn0seKdglwQ8lL0fNRlOV3BWobrzENAr2HPI1egsY1dhlH1CkPvzdxMkjmeSyrGYt5ac4tK1IO++RAeefsBPAETdY89C3lfbcy3ApfsG5GwLkQE
  template:
    metadata:
      creationTimestamp: null
      name: slack-webhook-url
      namespace: server
