# This manifest is only meant to be used as a template for defining sync configurations
# in ./k8s/server/ephemeral-instances/ directory. The dev-test must be subsituted
# with the appropriate branch name.

# It should be not applied directly to the cluster
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dev-test
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: dev-test
  secretRef:
    name: flux-system
  url: ssh://git@github.com/PHACDataHub/cpho-phase2
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev-test-infra
  namespace: flux-system
spec:
  path: ./k8s/server/overlays/ephemeral/infrastructure
  interval: 2m0s
  prune: true
  sourceRef:
    kind: GitRepository
    name: dev-test
  wait: true
  dependsOn:
    - name: ephemeral-instances
  postBuild:
    substitute:
      BRANCH_NAME: dev-test
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev-test-postgres
  namespace: flux-system
spec:
  path: ./k8s/server/overlays/ephemeral/postgres
  interval: 2m0s
  prune: true
  sourceRef:
    kind: GitRepository
    name: dev-test
  wait: true
  dependsOn:
    - name: dev-test-infra
  postBuild:
    substitute:
      BRANCH_NAME: dev-test

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev-test-django
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./k8s/server/overlays/ephemeral/django
  prune: true
  sourceRef:
    kind: GitRepository
    name: dev-test
  dependsOn:
    - name: dev-test-postgres
  decryption:
    provider: sops
  postBuild:
    substitute:
      BRANCH_NAME: dev-test
---
# The following manifests are only required if there's a need to enable automated
# image updates for ephemeral deployments.

# Note that you'll also need to update the policy name in the `$imagepolicy` comment
# next to spec.template.spec.image in your branch's server deployment located
# at ./k8s/server/overlays/ephemeral/django/deployment.yaml
# See https://fluxcd.io/flux/guides/image-update/ for details
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: dev-test-server
  namespace: flux-system
spec:
  filterTags:
    extract: $ts
    pattern: ^dev-test-[a-fA-F0-9]+-(?P<ts>.*)
  imageRepositoryRef:
    name: server
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: dev-test-cpho-updater
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: dev-test
  interval: 5m
  update:
    strategy: Setters
    path: .
  git:
    checkout:
      ref:
        branch: dev-test
    commit:
      author:
        name: fluxbot
        email: fluxcd@users.noreply.github.com
      messageTemplate: "[ci skip] {{range .Changed.Changes}} {{println .NewValue}}{{end}}"
    push:
      branch: dev-test
