trigger: none

pool: spib-sdse-hopic-agents-dv

resources:
  repositories:
    - repository: templates
      type: github
      name: PHACDataHub/ADO-Pipeline-Templates
      # Service connection to GitHub configured in Azure DevOps
      endpoint: DMIA
    - repository: test_secret_check
      type: github
      name: PHACDataHub/ADO-Pipeline-Templates
      ref: refs/heads/tm-secret-expiry-check
      endpoint: DMIA

steps:
- script: |
    curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
  displayName: Install AZ CLI

- template: run_bash_secret_expiry_check.yaml@test_secret_check
  parameters:
    azureSubscription: SPIB-SDSE-HOPIC-CICDLZSP-DT
    warningDays: 30
    appNames:
    - 'SPIB-SDSE-HOPIC-CICDLZSP-DT'
    - 'CDSB-DMIA-HOPIC-SSO-pr'
    - 'CDSB-DMIA-HOPIC-SSO-dv'
    - 'HOPIC/CPHO'
