apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flux-crds.yaml
- sync-config.yaml
- deployment-config.yaml

patches:
  # enable istio injection for the namespace
  - target:
      kind: Namespace
      name: flux-system
    patch: |-
      - op: replace
        path: /metadata/labels
        value:
          istio.io/rev: asm-managed
