apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flux-crds.yaml
- gcr-sync.yaml
- sync-config.yaml
- deployment-config.yaml

patches:
  # enable istio injection for the namespace
  - target:
      kind: Namespace
      name: flux-system
    # use ~1 instead of / in path (see https://github.com/kubernetes-sigs/kustomize/issues/1256)
    patch: |-
      - op: add
        path: /metadata/labels/istio.io~1rev
        value: asm-managed
