apiVersion: v1
data:
  secret-key: ENC[AES256_GCM,data:+3TMLnB3aGzyUPKqkjFY2W+MEErKppfBdMpn4LZ7cFKMfPpYmWQO8YLb4iaw3oXDpQMNVrM6zfx7EojCJkL3+RYL+LJrl7Ya,iv:AEEjGHRdwd1ASlwy+12yEkec3mSSkM9wMTJDqoAxbhg=,tag:QEzr7j6wRCa0aZyc0JJDpg==,type:str]
kind: Secret
metadata:
  labels:
    app: server
  name: django-secret-key
  namespace: server
sops:
  age: []
  azure_kv: []
  encrypted_regex: ^(data|stringData)$
  gcp_kms:
  - created_at: "2023-12-12T18:45:36Z"
    enc: CiQABjWkUI/cDqGciCkvX2TljiXkDNnm7I5mM1kqs4Px2Qc0ESUSSQB/rzHLa302yTHjS0tBM/95N9PDTeG4zhyYdUQ/GJYx4v2hZmrloAmPRD5Ioz4GbI2Zg1UgWvR9y8DaUWxX/ptdknTLVrfMDZU=
    resource_id: projects/phx-01h4rr1468rj3v5k60b1vserd3/locations/northamerica-northeast1/keyRings/sops/cryptoKeys/sops-key
  hc_vault: []
  kms: []
  lastmodified: "2023-12-12T18:45:36Z"
  mac: ENC[AES256_GCM,data:wHnK4XuiObfZG7CK2+bAZIIb2REYfpwluLn7hVwJx6+rtLb69H1aELAJpdD5WQAqB+7JhMjUPWBDsUYHBO7kkoL+PMSYDlJ0R70p+rHfCQgo2SpBBAh5BvYRuwmYH6hpQ+wsOQ7hvn2RSNpKUtQyYoSh2lThsF0IFDB1+Iobbh4=,iv:KMEem2wwdrE/+DOkE+uiz6b2B/IDImiR89XYGJa85/g=,tag:Sdq4HawBj/PLfJzVliZDCg==,type:str]
  pgp: []
  version: 3.8.1
type: Opaque
---
apiVersion: v1
data:
  client-id: ENC[AES256_GCM,data:64aUQ2UwOW8xq2ajiWbtyWi8h2egdqsVdaHIDWCrme+R/RXZHDwP2bZqlk5+hy/L,iv:cXVbvgvOoy4yZNdiqu4G6s5U1Lf6+9pyH8Qw83sd/ME=,tag:Sp4h135YCNDNA1qQXEYJJg==,type:str]
  client-secret: ENC[AES256_GCM,data:bj8EdYVMslI/pjI+aVAE0AVscqqvBlaylcx91iLAlFHspPXy+9D3IgIgktpOl2dQizZk91oOgJs=,iv:XPcNs93dJYcW3AnqLWMoErUP4BNG5EhDZhmdoKbPPAk=,tag:2B63iD4Bby54mzD7s3inVQ==,type:str]
  microsoft-tenant: ENC[AES256_GCM,data:URjlYy/5Xxo15WpbrrkLVb2qDgDiYHsZeFZgmJR7CO9O7oSIYzu+/YauBqfmoZo1,iv:1izXDyxhHwS0sBGsaFjEcWkTdFlRsnLN9QrU0EjvvJ4=,tag:DMMdilfBGAgPBBnB1U44Hw==,type:str]
kind: Secret
metadata:
  labels:
    app: server
  name: phac-aspc-oauth-config
  namespace: server
sops:
  age: []
  azure_kv: []
  encrypted_regex: ^(data|stringData)$
  gcp_kms:
  - created_at: "2023-12-12T18:45:36Z"
    enc: CiQABjWkUI/cDqGciCkvX2TljiXkDNnm7I5mM1kqs4Px2Qc0ESUSSQB/rzHLa302yTHjS0tBM/95N9PDTeG4zhyYdUQ/GJYx4v2hZmrloAmPRD5Ioz4GbI2Zg1UgWvR9y8DaUWxX/ptdknTLVrfMDZU=
    resource_id: projects/phx-01h4rr1468rj3v5k60b1vserd3/locations/northamerica-northeast1/keyRings/sops/cryptoKeys/sops-key
  hc_vault: []
  kms: []
  lastmodified: "2023-12-12T18:45:36Z"
  mac: ENC[AES256_GCM,data:wHnK4XuiObfZG7CK2+bAZIIb2REYfpwluLn7hVwJx6+rtLb69H1aELAJpdD5WQAqB+7JhMjUPWBDsUYHBO7kkoL+PMSYDlJ0R70p+rHfCQgo2SpBBAh5BvYRuwmYH6hpQ+wsOQ7hvn2RSNpKUtQyYoSh2lThsF0IFDB1+Iobbh4=,iv:KMEem2wwdrE/+DOkE+uiz6b2B/IDImiR89XYGJa85/g=,tag:Sdq4HawBj/PLfJzVliZDCg==,type:str]
  pgp: []
  version: 3.8.1
type: Opaque
---
apiVersion: v1
data:
  token: ENC[AES256_GCM,data:hhRznkudQpslHS4MC5vgudW3sh1FWGqWqalWFDtJErdodBygEKWxtZu/bNhC/Dk+JwAdfVmXdqQdd5/XubgVo5NjjCae0e7RedTV+g==,iv:EsoHxaT1gs+mk1XR/G7Ha5wIi1pbh01E/yTxhSgqaek=,tag:wUrpWDtPUrcdamePJo7WtQ==,type:str]
kind: Secret
metadata:
  labels:
    app: server
  name: slack-alerting-app-token
  namespace: server
sops:
  age: []
  azure_kv: []
  encrypted_regex: ^(data|stringData)$
  gcp_kms:
  - created_at: "2023-12-12T18:45:36Z"
    enc: CiQABjWkUI/cDqGciCkvX2TljiXkDNnm7I5mM1kqs4Px2Qc0ESUSSQB/rzHLa302yTHjS0tBM/95N9PDTeG4zhyYdUQ/GJYx4v2hZmrloAmPRD5Ioz4GbI2Zg1UgWvR9y8DaUWxX/ptdknTLVrfMDZU=
    resource_id: projects/phx-01h4rr1468rj3v5k60b1vserd3/locations/northamerica-northeast1/keyRings/sops/cryptoKeys/sops-key
  hc_vault: []
  kms: []
  lastmodified: "2023-12-12T18:45:36Z"
  mac: ENC[AES256_GCM,data:wHnK4XuiObfZG7CK2+bAZIIb2REYfpwluLn7hVwJx6+rtLb69H1aELAJpdD5WQAqB+7JhMjUPWBDsUYHBO7kkoL+PMSYDlJ0R70p+rHfCQgo2SpBBAh5BvYRuwmYH6hpQ+wsOQ7hvn2RSNpKUtQyYoSh2lThsF0IFDB1+Iobbh4=,iv:KMEem2wwdrE/+DOkE+uiz6b2B/IDImiR89XYGJa85/g=,tag:Sdq4HawBj/PLfJzVliZDCg==,type:str]
  pgp: []
  version: 3.8.1
type: Opaque
---
apiVersion: v1
data:
  slack-url: ENC[AES256_GCM,data:Z2syNF1WYnSAkdjokPsYZK4nUS2vVynVneHWX8JFTw3UxXO8dZ9uqBwXuqZIocmmDrfWqokjqXL8TOFWwyRmpp15GoEXnUxSQD/gq2jamzMyo1cjdCDZ7YCmqK4RQXg/VwpmPmQCtsbkvWIR,iv:MHBR+/phj8I9CgXGmkRglC6vBXD8ZtM7GSB12lc9DP0=,tag:zeXn9c7ZiZ0gZa6TKOdehQ==,type:str]
kind: Secret
metadata:
  labels:
    app: server
  name: slack-webhook-url
  namespace: server
sops:
  age: []
  azure_kv: []
  encrypted_regex: ^(data|stringData)$
  gcp_kms:
  - created_at: "2023-12-12T18:45:36Z"
    enc: CiQABjWkUI/cDqGciCkvX2TljiXkDNnm7I5mM1kqs4Px2Qc0ESUSSQB/rzHLa302yTHjS0tBM/95N9PDTeG4zhyYdUQ/GJYx4v2hZmrloAmPRD5Ioz4GbI2Zg1UgWvR9y8DaUWxX/ptdknTLVrfMDZU=
    resource_id: projects/phx-01h4rr1468rj3v5k60b1vserd3/locations/northamerica-northeast1/keyRings/sops/cryptoKeys/sops-key
  hc_vault: []
  kms: []
  lastmodified: "2023-12-12T18:45:36Z"
  mac: ENC[AES256_GCM,data:wHnK4XuiObfZG7CK2+bAZIIb2REYfpwluLn7hVwJx6+rtLb69H1aELAJpdD5WQAqB+7JhMjUPWBDsUYHBO7kkoL+PMSYDlJ0R70p+rHfCQgo2SpBBAh5BvYRuwmYH6hpQ+wsOQ7hvn2RSNpKUtQyYoSh2lThsF0IFDB1+Iobbh4=,iv:KMEem2wwdrE/+DOkE+uiz6b2B/IDImiR89XYGJa85/g=,tag:Sdq4HawBj/PLfJzVliZDCg==,type:str]
  pgp: []
  version: 3.8.1
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: server
  name: server
  namespace: server
spec:
  ports:
  - name: http-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: server
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server
  name: server
  namespace: server
spec:
  selector:
    matchLabels:
      app: server
  strategy: {}
  template:
    metadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "false"
      labels:
        app: server
    spec:
      containers:
      - image: auto
        name: istio-proxy
        resources:
          requests:
            cpu: 50m
            memory: 112Mi
      - env:
        - name: IS_K8S
          value: "true"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secret-key
              name: django-secret-key
        - name: ALLOWED_HOSTS
          value: hopic-sdpac.phac-aspc.alpha.canada.ca,34.149.100.163,localhost,34.152.0.41,41.0.152.34.bc.googleusercontent.com
        - name: SLACK_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              key: slack-url
              name: slack-webhook-url
        - name: DB_NAME
          value: cpho-phase2_db
        - name: DB_HOST
          value: cpho-postgres14-cluster-rw
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: cpho-postgres14-cluster-app
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: cpho-postgres14-cluster-app
        - name: PHAC_ASPC_OAUTH_PROVIDER
          value: microsoft
        - name: PHAC_ASPC_OAUTH_APP_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: client-id
              name: phac-aspc-oauth-config
        - name: PHAC_ASPC_OAUTH_APP_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: client-secret
              name: phac-aspc-oauth-config
        - name: PHAC_ASPC_OAUTH_MICROSOFT_TENANT
          valueFrom:
            secretKeyRef:
              key: microsoft-tenant
              name: phac-aspc-oauth-config
        - name: ENABLE_LEGACY_LOG_IN
          value: "true"
        image: northamerica-northeast1-docker.pkg.dev/phx-01h4rr1468rj3v5k60b1vserd3/cpho-phase2-artifact-registry-for-cloud-run/cpho-phase2:a11y-testing-b627c606-1702064694
        name: server
        readinessProbe:
          httpGet:
            httpHeaders:
            - name: Host
              value: hopic-sdpac.phac-aspc.alpha.canada.ca
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 35
          periodSeconds: 10
          timeoutSeconds: 3
        resources:
          requests:
            cpu: 200m
            memory: 400Mi
        securityContext:
          runAsUser: 5678
status: {}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: server
  name: server
  namespace: server
spec:
  maxReplicas: 8
  metrics:
  - resource:
      name: memory
      target:
        averageUtilization: 65
        type: Utilization
    type: Resource
  - resource:
      name: cpu
      target:
        averageUtilization: 65
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: server
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    app: server
  name: server-virtual-service
  namespace: server
spec:
  gateways:
  - istio-ingress/public-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /
    name: gateway-to-server
    route:
    - destination:
        host: server.server.svc.cluster.local
