apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: server
    istio.io/rev: asm-managed
  name: server
spec: {}
status: {}
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  labels:
    app: server
  name: cpho-postgres14-cluster
  namespace: server
spec:
  backup:
    barmanObjectStore:
      destinationPath: gs://hopic-dev-postgres-backup
      googleCredentials:
        gkeEnvironment: true
    retentionPolicy: 30d
  bootstrap:
    initdb:
      database: cpho-phase2_db
      owner: cpho-phase2_db_user
  imageName: ghcr.io/cloudnative-pg/postgresql:14.9
  inheritedMetadata:
    annotations:
      proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
      sidecar.istio.io/proxyCPU: 50m
      sidecar.istio.io/proxyMemory: 112Mi
  instances: 3
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: false
  postgresql:
    parameters:
      auto_explain.log_min_duration: 10s
      log_checkpoints: "on"
      log_connections: "on"
      log_disconnections: "on"
      log_hostname: "on"
      log_lock_waits: "on"
      log_min_messages: error
      log_temp_files: "0"
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
      pgaudit.log: all, -misc
      pgaudit.log_catalog: "off"
      pgaudit.log_parameter: "on"
      pgaudit.log_relation: "on"
      shared_buffers: 256MB
    pg_hba:
    - host all all all md5
  primaryUpdateStrategy: unsupervised
  resources:
    requests:
      cpu: 450m
      memory: 1926Mi
  serviceAccountTemplate:
    metadata:
      annotations:
        iam.gke.io/gcp-service-account: hopicpostgresbackup@phx-01h4rr1468rj3v5k60b1vserd3.iam.gserviceaccount.com
  startDelay: 900
  stopDelay: 900
  storage:
    size: 2Gi
    storageClass: standard
