apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  strategy: {}
  template:
    metadata:
      annotations:
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
    spec:
      serviceAccountName: server
      securityContext:
        runAsNonRoot: true
      containers:
        # istio-proxies are injected by anthos, see `istio.io/rev: asm-managed` in ../namespace.yaml
        # these are overrides for the default configuration of those injected proxy sidecars
      - name: istio-proxy
        image: auto
        resources:
          requests:
            # Experiment: using the minimum pod resources https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-resource-requests#compute-class-min-max
            cpu: 50m # + `server` container = 250m
            memory: 112Mi # + `server` container = 512MiB
        securityContext:
          allowPrivilegeEscalation: false
      - name: server
        securityContext:
          runAsUser: 65532
          allowPrivilegeEscalation: false
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secret-key
              key: secret-key
        - name: SLACK_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: slack-webhook-url
              key: slack-url
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: cpho-postgres14-cluster-app
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cpho-postgres14-cluster-app
              key: password
        - name: PHAC_ASPC_OAUTH_APP_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: phac-aspc-oauth-config
              key: client-id
        - name: PHAC_ASPC_OAUTH_APP_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: phac-aspc-oauth-config
              key: client-secret
        - name: PHAC_ASPC_OAUTH_MICROSOFT_TENANT
          valueFrom:
            secretKeyRef:
              name: phac-aspc-oauth-config
              key: microsoft-tenant
        readinessProbe:
          httpGet:
            path: /healthcheck/
            port: 8080
            httpHeaders:
            - name: Host
              value: hopic-sdpac.phac-aspc.alpha.canada.ca
          initialDelaySeconds: 135
          periodSeconds: 10
          timeoutSeconds: 3
status: {}
