apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-alerting-app-token
  namespace: server
spec:
  encryptedData:
    token: AgBXLkxIEYgvfLfD9R3K2p9zPLE5VnICbIhp9NW1YM+JebyEPFQjburMo6NKv9Lrc1PCpT0cXvM0HukgOt1mu5P8dWo4aRHcT+g+ED/1hMAungIM308EQUR8xtk974m9FHGecVHeitkB/KKXtSRtBok7Kn1Gi33ad4+YTie5qbrhz7a9Qr+y351nlGPUyysrNv7dbfCTI2MkMTzurXQyuTnmZAJHfK2LM8EmWyQ8jNe1nbtOsdy/geLAngSCZ5n2pVXg8mdAHx/5eXTFO+0AV+g37fgGSoYHTsrdyMWcAeIpc5OtXaL71AdKLBcVNPzZEsN3NLfMYb2LMCG0dmRXAlQyaADEJ+5eo6JN/RICyfDNZS+oXwsiXzGmTknH3BkmEf5le6ajsDmVMhh4Be8M/BowLRuuAhgOsWTa+7DJnTBTaqHbFckY9SmsbBuitw1EaYBdgZzumum1spN3010h9Kh0bDUZ1qH0nsgN9TZubHA8z2vWZ6ykDbngnvgnralita6rhUWivWeRWy+TOdMed4NWWd5/nUZlHQD+U8XInxyiLB5YZLMi73k4d1U70X1AreJvVUzYHrkliJSxmYVFiAK+mKtPKrqmoApbeKEJOkqez9C5aESyDQHah31MbMHa5/Z0PULsU87BLlAT17NF+paLQir4seOH/WmiaMKOSaueH9yWRZIkZJPrtzdgJ+ZkzBj80vLrQpp0LAcCLE8ROB2+ZQsMm5HUDkDcLxmwEBmHAKYkHxx3pf66x+rePIShL8eA4Z9R5aFx0A==
  template:
    metadata:
      creationTimestamp: null
      name: slack-alerting-app-token
      namespace: server
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: django-secret-key
  namespace: server
spec:
  encryptedData:
    secret-key: AgBlkhtbHjV31R8NMwMY2714LEaZOYqSOXaJ4HqdGh5nVtfAUTB7zSlxo9KMQTmYoJN19zlsDuib8hpLwpN4k2GorqKIlH+SmQlpuiy8ObfUdTETVzqVADe79ejYsDPbJSSDpKUDMb5dJ3FhhC/oDbGUnK7KKZBVcjECW0MQnf+ghAUkBEHVaIxBuvmt3Np3gwVE4huh1ZQXVY4ReQW5wFrZtKjgCzPAY+FRd+AughnuUWN0mk9Fojzk9F+JEJzyJnXG2ELLV5VMSEGq5aGaVDJ+dZOkV90mY0wkhqdmO7UMdL6z8V9wBNW+ReajbQ5OzyvtE4BxpCR8elvVJ8qg5NyJRmO0Opf3E9Q5QAy9kRnPtdfAclz1wCtCoUv962JXe8ryS46CNXLD3skC8EoZrC/eUapyg0wHoUBWj4w5tcvgtNeDpgmvel0qw6aE1iovDpGeQqqXsOoCKv6C8Ajz7omSXbSjQu3guHd31B6uVk83ZBeNo6fCNbKdRzKIqdSj/s60Ht2k91JdrZsWx7yIrIxzh0n7WA6JyCNSOcWv6oKNHMubHlSTL7U7sSvmas9D/oAxQZ35JlVjDJ3iMfbnO6unqHbtvmHYfSeBU6LzsNOxW5WTwfXB4lAaJk276TvMZyBvNxe/UlOY9bec33IzYzZeU/SNzJXMFWih8Jy5Tc2f+SOGU0YpoJcsRiRRRi1DmJnRNBi07zLu7WEGg7XySn/J5okfSWQeFGs7493Uk2S3FBN89pWXKMcVlchuxvCVGtCRJbNWN0c=
  template:
    metadata:
      creationTimestamp: null
      name: django-secret-key
      namespace: server
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-webhook-url
  namespace: server
spec:
  encryptedData:
    slack-url: AgCeeluEPmiFL46ZrW/LvtgN5eLfA83odK/4DRxUTcgyG4d45B33zWCtpbKHoZieVfUU2HDD8M/DTd3IcLDJ1ElXxr/AhpxLFuwIjsEgnTXEFys8amBbGMm8rmcr2E/OWaEugo6uaE3PfTRlk8ykXWHxcbRRYyuPGXLlPshw/CNdb7HMkCBnjqR4KVQG0E3w4/FfbEUouSabBIRMluvzyyPSmfj4ZosLrejFJsP4pCAxNw02R6ylqvPOT/OMB9Fb0oA3msg4sBqHGbbvhZZ2Daos1Bt3NZiipry4E4yStSbqORFY3hNxt+xfPLSRPe2it9HyaD4k6kATqudQy3DWF/FFrRY7GsO/ybnPWli8VJYGagFqbm/N0kwkM3vYzrc4JEN26D16/3O3Avzr+gUtb2P+4ZyLVLB4iGgHVrVABiXGcypDOG8QpbwBjtqOF4F+yl3764nBhJaLgzX44uVvRpqid0Rev6eaxBLFdJLuXBybedQiew4zXj+FEU9pfA3P7RH4BWTCleI+C+NtSoZyIYd8q0+mfC2DMoWEbNzoe28fPZCaRkGRfeuYnpPeYQJpj+FNqB0MaUQsEYfZIhyE+UJ2aSCB+bfCK7b9KYGqK2i1eEw6KesQlliYB70edKX5ViWLRni6+zk5QA9XXIkvUPRKl4XoQCP4SXofq/dUu+AfPXZwOHraIBLoSxd/7Sn0seKdglwQ8lL0fNRlOV3BWobrzENAr2HPI1egsY1dhlH1CkPvzdxMkjmeSyrGYt5ac4tK1IO++RAeefsBPAETdY89C3lfbcy3ApfsG5GwLkQE
  template:
    metadata:
      creationTimestamp: null
      name: slack-webhook-url
      namespace: server
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: phac-aspc-oauth-config
  namespace: server
spec:
  encryptedData:
    client-id: AgAktIUgcNWMxm9407Y8XN5hP/Jm07P8U79kNAV7qHrFqD26ysM0/qtD5V28ksdpVuRahL0T/wqKx1m/icyawbetY7dZlfPOHj4g291lcmYh5yLal2diAPv/6ckUX3oprugpH6+0CmbfxHkc6YCV9Slk/jdjZl04W0VAHgYL7vLFRfvy6+C0lRZlrrQ/ztxEcXLuLVEEsQXpQ1bwEJAVf9FN/2Ul4B2oMnXYFQm9c5oepVFUog09X/5C5+FjG52dziLNl0NA/3+Guulo50FLyT5M3L3HtqHi1TZ8wNYBTZmcLAO3EUKnKoDi/MKngmJAMsDsxgVFAD3YRLiqkMwhhDz/kCxITaPNLxbz2CA9H/qDBC+W6YxGNEHcG6fHPz5oyeNgdFrnfOYegtMzruWTpHJWdZqaoE4+t5aPHBQJxipm7QioG8R4zUoRESTmxnqNp50JWKFOdFaJmNu/vEnrCgGc/JeIKatZmgHARi3nq+2u8ALzYSnxz4xyDIDoyd528oDFTzS3U8gAwthP9L9/GCW+aCb9K1xvl7UpV9MiSJ532GzgTsf6vMLm5RGfhioR5i8e9+JKHvGHrbW1UewmIK9go+D9QMEiU3Lyp2Voeb2aZN0Yc0jArtEr8aibOg+guhgv2qndXD3CVblCZye43vcIfGD/cCv8s6qS+A+XI0RLtn73w+4tW7mv14U7XSDqC35cvOFZvAfvutD6OBgfnWaB5eoHLn6APTiJjQFfqQCEgTFLrtU=
    client-secret: AgBCt6np8tuDqwf/kCRJxgWh1oJ9ytYfaGXtoj1hz1BlSa1BXt7ZzDlWC7ggMRcQKt8HQFgXRsRsEfeLsJ7QkPFn2T6yYdutkuA6XKUsAnx6qnjp88z82+uoS103ez/BIqT889j9alAuE0yNFNTuA35NOW2BaWJFFc3Jqz+6ZfSWyiv7kxgcFyvh9x+z+yT851dnUzGZD60jeH4DeWO5JXQs6nfHUw3heI8M0NZCF5aNTB3+SQKTGepevdO4hXdBr40L4RbJQVumSPN4JY+QVO9TCOuBPek+b7zbFQrSi2WgN2jko1T63JVIdc0IcjsPCkMuk427D44gYKZTV6tivtckpwtdkGgSzh9IcS2MxRhonnQjtoLsEifLOG58Xa3SRtQFy8kYHlkVxqvSu9oWanifglKp+WW0Ym8T4vVyW7pj/EjQW2Bg4AfgbvFUO/2uydChgP7ZaEN43vMxueoR+Wz1ceMymkIWVtC3XtIO346q9MuIXOHlzrKfJ8DsRZJ12cWTSMO6sGDnuAYp9vC/pTsCV74WtpmrF04SB0ueXTAjaPfJ8WgC+EAWCMveQrpl2AATdR8O5a8XBDBGDeGx0aNN3tt3M9OC/BbWg+oC3qReSI+tCwMJSdIm0LzacxQZk5asBSUN9SHoZMVDz+IEpNxxw30nPwVZX31xxikuvO5n5oKUzZFdD/csIQuUHco4soPO2YIZVGH2+5V1jvhpzeR8BuaV/vGhEw5rZXCQyXy+vxNaIgkAC8qntPU=
    microsoft-tenant: AgBWdPz8FYYxynNrCnQgXeYaMtUtWH8CevwWJmUoeYQeD4Ux2bTrDa4vJmIvmYo8sYXY6N5lVFu+/LW9s17n07neiOKZzstdA801X72OrGDsF9/u1oLxmkevHDy0Qiz5JsfU3NxKj3sNxIOrq5kZJrUJmNH9b50M0F1iJb+wH2dI+Jlmx3vQir9yORm63+5VViyJ1tTy0pPn75uc0zqg+h6Taf8lyK1wGKSs/gVfHgmtTjyTqJMWnwKqAU2f6PlktOUzhjlpHflE+hhc+Qo0HQO/PduxQrYraTk4ofUkssetk1PR/5ja8PKGL/GBZEU4h/6acuyn2MjUFSl+tfS1C5JwRZJstHsv0bvtoU5rzR3At2YuQNQ3HKwqwfVJux+IM5cwMc8iS3zbSGJoKxsJSgyNoHE4ahGRqzhnfLH9UD496E/eReLeZV0zw0RD1wJ/rtwSmYYneXEBgd58ag85vu0sNYkJqt4LGed4EQc7d9sSf04el74XjHik7Wly4okkTXDXv9HsidOslvgz3VF6FqpXuAY5chQiUANbQVERrIysAtSwk/6HRz+dbcPScoqlwr2F6IZoyNd5wwJzExoTJl2fS3XaZ/onNcwa/TxJU7xC1FJaIUuNHKZfp2FY+6aGy6vTZn5BqRaPkTN9tdZ3jx4e0WRM8cUQ+RjMqpGyM0tQxIGRSiAiucrPDG9jhYtd3FBTKhqZDO1QdMqz5dZ38mKR1UBHi1tkOz6mq7UEeIsFmb6A/38=
  template:
    metadata:
      creationTimestamp: null
      name: phac-aspc-oauth-config
      namespace: server


