apiVersion: v1
kind: Service
metadata:
  labels:
    app: server
  name: server
spec:
  ports:
  - name: http-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: server
  type: ClusterIP
status:
  loadBalancer: {}
