apiVersion: v1
data:
  mesh: |-
    defaultConfig:
      image:
        imageType: default
      tracing:
        stackdriver: {}
    discoverySelectors:
    - matchLabels:
        istio-injection: enabled
kind: ConfigMap
metadata:
  name: istio-asm-managed-rapid
  namespace: istio-system

