apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
    spec:
      containers:
      - image: northamerica-northeast1-docker.pkg.dev/pdcp-cloud-006-cpho/cpho/frontend:test-0000
        name: frontend
        resources: {}
status: {}
