apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnectorContext
metadata:
  # you can only have one ConfigConnectorContext per namespace
  name: configconnectorcontext.core.cnrm.cloud.google.com
  namespace: cnrm-system
spec:
  googleServiceAccount: "resourceprovisioner@phx-01h4rr1468rj3v5k60b1vserd3.iam.gserviceaccount.com"
