# Ref: https://cloudnative-pg.io/documentation/1.21/recovery/#recovery-from-an-object-store
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cpho-postgres14-cluster
spec:
  instances: 1
  startDelay: 900
  stopDelay: 900

  postgresql:
    pg_hba:
      - host all all all md5

  bootstrap:
    recovery:
      source: cpho-postgres-restore
      owner: cpho-phase2_db_user
      database: cpho-phase2_db

  storage:
    storageClass: standard
    size: 1Gi

  serviceAccountTemplate:
    metadata:
      annotations:
        # k8s service account is created with the same as `metadata.name` above
        # ensure an appropriate storage role(s) and workload identity is assigned: https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity
        iam.gke.io/gcp-service-account: hopic-postgres-backup@pht-01hp04dtnkf.iam.gserviceaccount.com

  externalClusters:
    - name: cpho-postgres-restore
      barmanObjectStore:
        serverName: cpho-postgres14-cluster
        destinationPath: gs://hopic-postgres-backup-01hp04dtnkf/
        googleCredentials:
          gkeEnvironment: true
        wal:
          maxParallel: 8
