# Generated by Django 4.1.9 on 2023-06-08 16:28

from django.db import migrations
import server.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cpho", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicatordatum",
            name="value",
            field=server.fields.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="indicatordatumhistory",
            name="value",
            field=server.fields.FloatField(null=True),
        ),
    ]
