# Generated by Django 4.0.6 on 2023-03-30 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpho', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='exports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
