# Generated by Django 4.1.9 on 2023-06-30 13:37

from django.db import migrations
import server.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cpho", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="period",
            options={"ordering": ["year", "quarter"]},
        ),
        migrations.RemoveField(
            model_name="periodhistory",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="periodhistory",
            name="name_fr",
        ),
        migrations.AddField(
            model_name="period",
            name="quarter",
            field=server.fields.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="period",
            name="year_type",
            field=server.fields.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="periodhistory",
            name="quarter",
            field=server.fields.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="periodhistory",
            name="year_type",
            field=server.fields.CharField(max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="period",
            unique_together={("year", "quarter", "year_type")},
        ),
        migrations.RemoveField(
            model_name="period",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="period",
            name="name_fr",
        ),
    ]
