# Generated by Django 4.1.9 on 2023-06-30 18:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "cpho",
            "0002_alter_period_options_remove_periodhistory_name_en_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="indicatordatum",
            unique_together={
                (
                    "indicator",
                    "period",
                    "dimension_type",
                    "literal_dimension_val",
                ),
                ("indicator", "period", "dimension_type", "dimension_value"),
            },
        ),
    ]
