# Generated by Django 4.1.9 on 2023-07-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cpho", "0003_alter_indicatordatum_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicatordatum",
            name="hso_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="indicatordatum",
            name="program_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="indicatordatumhistory",
            name="hso_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="indicatordatumhistory",
            name="program_approved",
            field=models.BooleanField(default=False),
        ),
    ]
