# Generated by Django 4.1.9 on 2023-07-20 20:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cpho", "0004_indicatordatum_hso_approved_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="indicatordatumhistory",
            old_name="approved",
            new_name="is_hso_approved",
        ),
        migrations.RenameField(
            model_name="indicatordatumhistory",
            old_name="hso_approved",
            new_name="is_program_approved",
        ),
        migrations.RemoveField(
            model_name="indicatordatum",
            name="hso_approved",
        ),
        migrations.RemoveField(
            model_name="indicatordatum",
            name="program_approved",
        ),
        migrations.RemoveField(
            model_name="indicatordatumhistory",
            name="program_approved",
        ),
    ]
