# Generated by Django 4.1.9 on 2023-07-27 19:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cpho", "0004_remove_indicatordatumhistory_approved_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dimensiontypehistory",
            options={"get_latest_by": "timestamp", "ordering": ["timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="dimensionvaluehistory",
            options={"get_latest_by": "timestamp", "ordering": ["timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="indicatordatumhistory",
            options={"get_latest_by": "timestamp", "ordering": ["timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="indicatorhistory",
            options={"get_latest_by": "timestamp", "ordering": ["timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="periodhistory",
            options={"get_latest_by": "timestamp", "ordering": ["timestamp"]},
        ),
        migrations.RemoveField(
            model_name="dimensiontypehistory",
            name="business_date",
        ),
        migrations.RemoveField(
            model_name="dimensiontypehistory",
            name="system_date",
        ),
        migrations.RemoveField(
            model_name="dimensionvaluehistory",
            name="business_date",
        ),
        migrations.RemoveField(
            model_name="dimensionvaluehistory",
            name="system_date",
        ),
        migrations.RemoveField(
            model_name="indicatordatumhistory",
            name="business_date",
        ),
        migrations.RemoveField(
            model_name="indicatordatumhistory",
            name="system_date",
        ),
        migrations.RemoveField(
            model_name="indicatorhistory",
            name="business_date",
        ),
        migrations.RemoveField(
            model_name="indicatorhistory",
            name="system_date",
        ),
        migrations.RemoveField(
            model_name="periodhistory",
            name="business_date",
        ),
        migrations.RemoveField(
            model_name="periodhistory",
            name="system_date",
        ),
    ]
