# Generated by Django 4.1.9 on 2023-08-21 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import server.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cpho", "0005_alter_dimensiontypehistory_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", server.fields.CharField(max_length=50)),
                ("geography", server.fields.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name="indicator",
            old_name="sub_category",
            new_name="topic",
        ),
        migrations.RenameField(
            model_name="indicatorhistory",
            old_name="sub_category",
            new_name="topic",
        ),
        migrations.AddField(
            model_name="indicatordatum",
            name="living_arrangement",
            field=server.fields.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name="indicatordatum",
            name="pt_data_availability",
            field=server.fields.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name="indicatordatum",
            name="value_displayed",
            field=server.fields.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="indicatordatumhistory",
            name="living_arrangement",
            field=server.fields.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name="indicatordatumhistory",
            name="pt_data_availability",
            field=server.fields.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name="indicatordatumhistory",
            name="value_displayed",
            field=server.fields.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="indicatordatum",
            name="data_quality",
            field=server.fields.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="indicatordatumhistory",
            name="data_quality",
            field=server.fields.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name="LocationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("type", server.fields.CharField(max_length=50)),
                ("geography", server.fields.CharField(max_length=50)),
                (
                    "edited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "eternal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="cpho.location",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
                "get_latest_by": "timestamp",
                "abstract": False,
            },
        ),
    ]
