# Generated by Django 4.1.9 on 2023-08-10 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import server.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cpho", "0005_alter_dimensiontypehistory_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PHACOrg",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=10, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name_en",
                    server.fields.CharField(default="", max_length=200),
                ),
                (
                    "name_fr",
                    server.fields.CharField(default="", max_length=200),
                ),
                (
                    "acronym_en",
                    server.fields.CharField(default="", max_length=20),
                ),
                (
                    "acronym_fr",
                    server.fields.CharField(default="", max_length=20),
                ),
                ("is_branch", models.BooleanField(default=False)),
                (
                    "parent",
                    server.fields.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cpho.phacorg",
                    ),
                ),
            ],
            options={
                "verbose_name": "public_health_org",
                "verbose_name_plural": "public_health_orgs",
            },
        ),
        migrations.CreateModel(
            name="PhacOrgRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_phac_org_lead", models.BooleanField(default=False)),
                (
                    "phac_org",
                    server.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cpho.phacorg",
                    ),
                ),
                (
                    "user",
                    server.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
