# Generated by Django 4.1.9 on 2023-08-22 18:06

from django.db import migrations
import server.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cpho", "0006_phacorg_phacorgrole_indicator_phacorg_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dimensionvalue",
            name="name_en",
            field=server.fields.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name="dimensionvalue",
            name="name_fr",
            field=server.fields.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name="dimensionvaluehistory",
            name="name_en",
            field=server.fields.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name="dimensionvaluehistory",
            name="name_fr",
            field=server.fields.CharField(max_length=75),
        ),
    ]
