# Generated by Django 4.1.9 on 2023-08-10 18:33

from django.db import migrations
import django.db.models.deletion
import server.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cpho", "0006_phacorg_phacorgrole"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicator",
            name="PHACOrg",
            field=server.fields.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="cpho.phacorg",
            ),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="PHACOrg",
            field=server.fields.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cpho.phacorg",
            ),
        ),
    ]
