# Generated by Django 4.1.9 on 2023-09-27 16:46

from django.db import migrations
import server.fields
import versionator.core


class Migration(migrations.Migration):
    dependencies = [
        ("cpho", "0008_rename_sub_category_indicator_topic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicator",
            name="relevant_dimensions",
            field=server.fields.ManyToManyField(to="cpho.dimensiontype"),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="relevant_dimensions",
            field=versionator.core.M2MTextField(default="[]"),
        ),
    ]
