# Generated by Django 4.1.9 on 2023-11-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cpho", "0009_indicator_relevant_dimensions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Name"
            ),
        ),
    ]
