# Generated by Django 4.1.9 on 2023-11-20 17:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cpho", "0010_alter_indicatordatum_unique_together_and_more"),
        ("cpho", "0010_user_name"),
    ]

    operations = []
