# Generated by Django 4.1.9 on 2023-12-01 20:28

from django.db import migrations
import server.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cpho", "0013_indicator_general_footnotes_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="benchmarking",
            unique_together={
                (
                    "indicator",
                    "oecd_country",
                    "is_deleted",
                    "deletion_time",
                    "labels",
                )
            },
        ),
        migrations.AddField(
            model_name="benchmarking",
            name="unit",
            field=server.fields.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="benchmarkinghistory",
            name="unit",
            field=server.fields.CharField(max_length=50, null=True),
        ),
    ]
