# Generated by Django 4.1.9 on 2024-01-24 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import server.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cpho", "0013_indicator_general_footnotes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrendAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", server.fields.CharField(max_length=50)),
                (
                    "year_range",
                    server.fields.CharField(max_length=50, null=True),
                ),
                ("data_point", server.fields.FloatField()),
                (
                    "line_of_best_fit_point",
                    server.fields.FloatField(null=True),
                ),
                (
                    "trend_segment",
                    server.fields.CharField(max_length=50, null=True),
                ),
                ("trend", server.fields.CharField(max_length=50, null=True)),
                ("is_deleted", server.fields.BooleanField(default=False)),
                (
                    "deletion_time",
                    server.fields.CharField(
                        default="", max_length=50, null=True
                    ),
                ),
                (
                    "indicator",
                    server.fields.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="cpho.indicator",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("indicator", "year", "is_deleted", "deletion_time")
                },
            },
        ),
        migrations.CreateModel(
            name="TrendAnalysisHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("year", server.fields.CharField(max_length=50)),
                (
                    "year_range",
                    server.fields.CharField(max_length=50, null=True),
                ),
                ("data_point", server.fields.FloatField()),
                (
                    "line_of_best_fit_point",
                    server.fields.FloatField(null=True),
                ),
                (
                    "trend_segment",
                    server.fields.CharField(max_length=50, null=True),
                ),
                ("trend", server.fields.CharField(max_length=50, null=True)),
                ("is_deleted", server.fields.BooleanField(default=False)),
                (
                    "deletion_time",
                    server.fields.CharField(
                        default="", max_length=50, null=True
                    ),
                ),
                (
                    "edited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "eternal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="cpho.trendanalysis",
                    ),
                ),
                (
                    "indicator",
                    server.fields.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cpho.indicator",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
                "get_latest_by": "timestamp",
                "abstract": False,
            },
        ),
    ]
