# Generated by Django 4.1.9 on 2024-01-24 16:33

from django.db import migrations
import server.fields


class Migration(migrations.Migration):
    dependencies = [
        (
            "cpho",
            "0014_alter_benchmarking_unique_together_benchmarking_unit_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="benchmarking",
            name="standard_deviation",
            field=server.fields.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="benchmarkinghistory",
            name="standard_deviation",
            field=server.fields.FloatField(null=True),
        ),
    ]
