# Generated by Django 4.1.9 on 2024-01-24 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import server.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cpho", "0015_alter_benchmarking_standard_deviation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndicatorDirectory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="IndicatorDirectoryLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "directory",
                    server.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cpho.indicatordirectory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IndicatorDirectoryUserAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "directory",
                    server.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cpho.indicatordirectory",
                    ),
                ),
                (
                    "user",
                    server.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "directory")},
            },
        ),
        migrations.RemoveField(
            model_name="phacorgrole",
            name="phac_org",
        ),
        migrations.RemoveField(
            model_name="phacorgrole",
            name="user",
        ),
        migrations.RemoveField(
            model_name="indicator",
            name="PHACOrg",
        ),
        migrations.RemoveField(
            model_name="indicatorhistory",
            name="PHACOrg",
        ),
        migrations.DeleteModel(
            name="PHACOrg",
        ),
        migrations.DeleteModel(
            name="PhacOrgRole",
        ),
        migrations.AddField(
            model_name="indicatordirectorylink",
            name="indicator",
            field=server.fields.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cpho.indicator",
            ),
        ),
        migrations.AddField(
            model_name="indicatordirectory",
            name="indicators",
            field=server.fields.ManyToManyField(
                through="cpho.IndicatorDirectoryLink", to="cpho.indicator"
            ),
        ),
        migrations.AddField(
            model_name="indicatordirectory",
            name="users",
            field=server.fields.ManyToManyField(
                through="cpho.IndicatorDirectoryUserAccess",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="indicatordirectorylink",
            unique_together={("indicator", "directory")},
        ),
    ]
