# Generated by Django 4.1.9 on 2024-01-26 19:02

import ckeditor.fields
from django.db import migrations
import server.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cpho", "0017_indicatordirectory_indicatordirectorylink_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicator",
            name="benchmarking_footnotes",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="benchmarking_legend",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="benchmarking_sources_english",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="impact_text",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="main_source_english",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="measure_text",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="other_relevant_sources_english",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="table_title_age",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="table_title_benchmark",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="table_title_education_household",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="table_title_income_quintiles",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="table_title_living_arrangement",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="table_title_province_territory",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="table_title_sex",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="table_title_trend",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="title_age",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="title_benchmark",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="title_education_household",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="title_income_quintiles",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="title_living_arrangement",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="title_overall",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="title_province_territory",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="title_sex",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="title_trend",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="trend_footnotes",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="visual_description_trend",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="x_axis_benchmark",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="x_axis_trend",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="y_axis_trend",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="benchmarking_footnotes",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="benchmarking_legend",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="benchmarking_sources_english",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="impact_text",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="main_source_english",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="measure_text",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="other_relevant_sources_english",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="table_title_age",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="table_title_benchmark",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="table_title_education_household",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="table_title_income_quintiles",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="table_title_living_arrangement",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="table_title_province_territory",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="table_title_sex",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="table_title_trend",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="title_age",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="title_benchmark",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="title_education_household",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="title_income_quintiles",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="title_living_arrangement",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="title_overall",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="title_province_territory",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="title_sex",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="title_trend",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="trend_footnotes",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="visual_description_trend",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="x_axis_benchmark",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="x_axis_trend",
            field=server.fields.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="y_axis_trend",
            field=server.fields.CharField(max_length=300, null=True),
        ),
    ]
