# Generated by Django 4.1.9 on 2024-01-31 17:39

from django.db import migrations
import server.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cpho", "0018_indicator_benchmarking_footnotes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicator",
            name="g1",
            field=server.fields.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="g2_lower",
            field=server.fields.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="g2_upper",
            field=server.fields.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="g3_lower",
            field=server.fields.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="g3_upper",
            field=server.fields.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="g4_lower",
            field=server.fields.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="g4_upper",
            field=server.fields.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="g5",
            field=server.fields.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="g1",
            field=server.fields.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="g2_lower",
            field=server.fields.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="g2_upper",
            field=server.fields.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="g3_lower",
            field=server.fields.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="g3_upper",
            field=server.fields.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="g4_lower",
            field=server.fields.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="g4_upper",
            field=server.fields.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="g5",
            field=server.fields.FloatField(null=True),
        ),
    ]
