# Generated by Django 4.1.9 on 2024-02-22 18:50

from django.db import migrations
import phac_aspc.django.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cpho", "0021_benchmarkinghistory_is_hso_submitted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicator",
            name="relevant_period_types",
            field=phac_aspc.django.fields.CommaSeparatedCharField(
                default="", max_length=250
            ),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="relevant_period_types",
            field=phac_aspc.django.fields.CommaSeparatedCharField(
                default="", max_length=250
            ),
        ),
    ]
