# Generated by Django 4.1.9 on 2024-02-29 17:59

from django.db import migrations
import server.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cpho", "0023_alter_indicator_impact_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dimensiontype",
            name="order",
            field=server.fields.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="dimensiontypehistory",
            name="order",
            field=server.fields.FloatField(default=0.0),
        ),
    ]
