# Generated by Django 4.1.9 on 2024-03-01 16:11

import ckeditor.fields
from django.db import migrations
import server.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cpho", "0024_dimensiontype_order_dimensiontypehistory_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicator",
            name="table_title_overall",
            field=server.fields.TextField(null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="table_title_overall",
            field=server.fields.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="impact_text",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="indicatorhistory",
            name="impact_text",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
