# Generated by Django 4.1.9 on 2024-03-01 16:48

from django.db import migrations
import django.db.models.deletion
import server.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cpho", "0025_indicator_table_title_overall_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="benchmarking",
            name="indicator",
            field=server.fields.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cpho.indicator",
            ),
        ),
        migrations.AlterField(
            model_name="indicatordatum",
            name="indicator",
            field=server.fields.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cpho.indicator",
            ),
        ),
        migrations.AlterField(
            model_name="trendanalysis",
            name="indicator",
            field=server.fields.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cpho.indicator",
            ),
        ),
    ]
