# Generated by Django 4.1.9 on 2024-03-01 17:16

from django.db import migrations
import server.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cpho", "0026_alter_benchmarking_indicator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicator",
            name="benchmarking_footnotes",
            field=server.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="benchmarking_sources_english",
            field=server.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="general_footnotes",
            field=server.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="impact_text",
            field=server.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="main_source_english",
            field=server.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="other_relevant_sources_english",
            field=server.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="trend_footnotes",
            field=server.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name="indicatorhistory",
            name="benchmarking_footnotes",
            field=server.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name="indicatorhistory",
            name="benchmarking_sources_english",
            field=server.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name="indicatorhistory",
            name="general_footnotes",
            field=server.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name="indicatorhistory",
            name="impact_text",
            field=server.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name="indicatorhistory",
            name="main_source_english",
            field=server.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name="indicatorhistory",
            name="other_relevant_sources_english",
            field=server.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name="indicatorhistory",
            name="trend_footnotes",
            field=server.fields.RichTextField(null=True),
        ),
    ]
