# Generated by Django 4.1.9 on 2024-03-25 15:09

from django.db import migrations
import server.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cpho", "0027_alter_indicator_benchmarking_footnotes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trendanalysis",
            name="year_range",
        ),
        migrations.RemoveField(
            model_name="trendanalysishistory",
            name="year_range",
        ),
        migrations.AlterField(
            model_name="trendanalysis",
            name="year",
            field=server.fields.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="trendanalysishistory",
            name="year",
            field=server.fields.CharField(max_length=50, null=True),
        ),
    ]
