# Generated by Django 4.1.9 on 2024-03-26 16:22

from django.db import migrations
import server.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cpho", "0027_alter_indicator_benchmarking_footnotes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="benchmarking",
            name="methodology_differences",
            field=server.fields.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="benchmarkinghistory",
            name="methodology_differences",
            field=server.fields.BooleanField(default=False),
        ),
    ]
