# Generated by Django 4.1.9 on 2024-03-25 16:32

from django.db import migrations
import server.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cpho", "0028_remove_trendanalysis_year_range_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trendanalysis",
            name="unit",
            field=server.fields.CharField(default="", max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trendanalysishistory",
            name="unit",
            field=server.fields.CharField(default="", max_length=75),
            preserve_default=False,
        ),
    ]
