# Generated by Django 4.1.9 on 2024-03-27 15:49

from django.db import migrations
import server.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cpho", "0030_alter_trendanalysis_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="benchmarking",
            name="methodology_differences",
            field=server.fields.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="benchmarkinghistory",
            name="methodology_differences",
            field=server.fields.BooleanField(default=False),
        ),
    ]
