# Generated by Django 4.1.9 on 2024-04-23 14:55

from django.db import migrations
import server.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cpho", "0032_indicator_pt_dynamic_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="benchmarking",
            name="year",
            field=server.fields.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="benchmarkinghistory",
            name="year",
            field=server.fields.IntegerField(null=True),
        ),
    ]
