# Generated by Django 4.1.13 on 2024-04-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cpho", "0033_alter_benchmarking_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="period",
            name="is_current",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="periodhistory",
            name="is_current",
            field=models.BooleanField(default=False),
        ),
    ]
