# Generated by Django 4.1.9 on 2024-05-02 15:46

from django.db import migrations
import server.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cpho", "0035_alter_trendanalysis_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="benchmarking",
            name="year",
            field=server.fields.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="benchmarkinghistory",
            name="year",
            field=server.fields.CharField(max_length=50, null=True),
        ),
    ]
