# Generated by Django 4.1.9 on 2024-05-22 01:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cpho", "0036_alter_benchmarking_year_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indicator",
            name="table_title_age_2",
        ),
        migrations.RemoveField(
            model_name="indicator",
            name="table_title_province_territory_2",
        ),
        migrations.RemoveField(
            model_name="indicator",
            name="table_title_sex_2",
        ),
        migrations.RemoveField(
            model_name="indicator",
            name="title_age_2",
        ),
        migrations.RemoveField(
            model_name="indicator",
            name="title_province_territory_2",
        ),
        migrations.RemoveField(
            model_name="indicator",
            name="title_sex_2",
        ),
        migrations.RemoveField(
            model_name="indicatorhistory",
            name="table_title_age_2",
        ),
        migrations.RemoveField(
            model_name="indicatorhistory",
            name="table_title_province_territory_2",
        ),
        migrations.RemoveField(
            model_name="indicatorhistory",
            name="table_title_sex_2",
        ),
        migrations.RemoveField(
            model_name="indicatorhistory",
            name="title_age_2",
        ),
        migrations.RemoveField(
            model_name="indicatorhistory",
            name="title_province_territory_2",
        ),
        migrations.RemoveField(
            model_name="indicatorhistory",
            name="title_sex_2",
        ),
    ]
