# Generated by Django 4.1.9 on 2024-05-16 18:57

from django.db import migrations
import server.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cpho", "0036_alter_benchmarking_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicatordatum",
            name="arrow_flag",
            field=server.fields.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="indicatordatumhistory",
            name="arrow_flag",
            field=server.fields.CharField(max_length=50, null=True),
        ),
    ]
