# Generated by Django 4.1.9 on 2024-06-05 18:52

from django.db import migrations
import django.db.models.deletion
import server.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cpho", "0039_custom_data_migration_flip_upper_lower_trend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="benchmarking",
            name="comparison_to_oecd_avg",
            field=server.fields.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="benchmarking",
            name="oecd_country",
            field=server.fields.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="cpho.country",
            ),
        ),
        migrations.AlterField(
            model_name="benchmarking",
            name="value",
            field=server.fields.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="benchmarkinghistory",
            name="comparison_to_oecd_avg",
            field=server.fields.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="benchmarkinghistory",
            name="value",
            field=server.fields.FloatField(null=True),
        ),
    ]
