# Generated by Django 4.1.13 on 2024-06-11 12:43

from django.db import migrations
import server.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cpho", "0040_alter_benchmarking_comparison_to_oecd_avg_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trendanalysis",
            name="data_point",
            field=server.fields.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="trendanalysis",
            name="unit",
            field=server.fields.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name="trendanalysishistory",
            name="data_point",
            field=server.fields.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="trendanalysishistory",
            name="unit",
            field=server.fields.CharField(max_length=75, null=True),
        ),
    ]
