# Generated by Django 5.0.6 on 2024-10-07 16:21

import server.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cpho", "0042_indicator_benchmarking_dynamic_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicator",
            name="name_fr",
            field=server.fields.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="indicatorhistory",
            name="name_fr",
            field=server.fields.CharField(max_length=100, null=True),
        ),
    ]
