# Generated by Django 5.0.9 on 2024-12-17 18:22

import server.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cpho", "0043_alter_indicator_name_fr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicator",
            name="sdg_goal",
            field=server.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="sdg_goal_fr",
            field=server.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="y_axis_trend_max",
            field=server.fields.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="y_axis_trend_min",
            field=server.fields.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="sdg_goal",
            field=server.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="sdg_goal_fr",
            field=server.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="y_axis_trend_max",
            field=server.fields.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="y_axis_trend_min",
            field=server.fields.FloatField(null=True),
        ),
    ]
