# Generated by Django 5.0.9 on 2025-01-16 16:14

import server.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cpho", "0044_indicator_sdg_goal_indicator_sdg_goal_fr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicator",
            name="table_title_grade",
            field=server.fields.TextField(null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="table_title_grade_fr",
            field=server.fields.TextField(null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="table_title_hospital_setting",
            field=server.fields.TextField(null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="table_title_hospital_setting_fr",
            field=server.fields.TextField(null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="title_grade",
            field=server.fields.TextField(null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="title_grade_fr",
            field=server.fields.TextField(null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="title_hospital_setting",
            field=server.fields.TextField(null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="title_hospital_setting_fr",
            field=server.fields.TextField(null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="table_title_grade",
            field=server.fields.TextField(null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="table_title_grade_fr",
            field=server.fields.TextField(null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="table_title_hospital_setting",
            field=server.fields.TextField(null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="table_title_hospital_setting_fr",
            field=server.fields.TextField(null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="title_grade",
            field=server.fields.TextField(null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="title_grade_fr",
            field=server.fields.TextField(null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="title_hospital_setting",
            field=server.fields.TextField(null=True),
        ),
        migrations.AddField(
            model_name="indicatorhistory",
            name="title_hospital_setting_fr",
            field=server.fields.TextField(null=True),
        ),
    ]
