# Generated by Django 5.1.4 on 2025-08-18 17:54

import server.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cpho", "0046_custom_data_migration_values_countries_benchmarking"),
    ]

    operations = [
        migrations.AddField(
            model_name="dimensiontype",
            name="excel_code",
            field=server.fields.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="dimensiontypehistory",
            name="excel_code",
            field=server.fields.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="dimensionvalue",
            name="excel_code",
            field=server.fields.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="dimensionvaluehistory",
            name="excel_code",
            field=server.fields.CharField(max_length=100, null=True),
        ),
    ]
