# Generated by Django 6.0.7 on 2026-08-07 15:19

import server.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cpho", "0047_dimensiontype_excel_code_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="benchmarking",
            options={
                "verbose_name": "Benchmarking",
                "verbose_name_plural": "Benchmarking",
            },
        ),
        migrations.AlterModelOptions(
            name="indicator",
            options={
                "verbose_name": "Indicator",
                "verbose_name_plural": "Indicators",
            },
        ),
        migrations.AlterModelOptions(
            name="indicatordatum",
            options={
                "verbose_name": "Indicator Data",
                "verbose_name_plural": "Indicator Data",
            },
        ),
        migrations.AlterModelOptions(
            name="trendanalysis",
            options={
                "verbose_name": "Trend Analysis",
                "verbose_name_plural": "Trend Analysis",
            },
        ),
        migrations.AddField(
            model_name="trendanalysis",
            name="arrow_flag",
            field=server.fields.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trendanalysishistory",
            name="arrow_flag",
            field=server.fields.CharField(max_length=50, null=True),
        ),
    ]
