apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cpho-postgres14-cluster
spec:
  # See for info regarding images: https://cloudnative-pg.io/documentation/1.22/#container-images
  # Images are found here: https://github.com/cloudnative-pg/postgres-containers/pkgs/container/postgresql
  imageName: ghcr.io/cloudnative-pg/postgresql:14.11
  primaryUpdateStrategy: unsupervised

# PostGres Best Practices for the Logging
  #  - https://www.enterprisedb.com/blog/how-get-best-out-postgresql-logs
  #  - https://medium.com/google-cloud/correlate-statement-logs-in-cloudsql-for-postgres-with-connection-sessions-5bae4ade38f5
  #  - PostgreSQL Official Documentation on pg_stat_statements: https://www.postgresql.org/docs/current/pgstatstatements.html
  #  - pgAudit GitHub Repository: https://github.com/pgaudit/pgaudit
  postgresql:
    parameters:
      log_min_messages: "warning" # From "error" to "warning" to reduce informational messages
      pg_stat_statements.track: top # From "all" to "top" to only track top-level statements
      auto_explain.log_min_duration: '30s' # From "10s" to "30s" to reduce slow query logs
      pgaudit.log: "all, -misc"
      log_connections: "off" # Reduced connection logs
      log_disconnections: "off" # Reduced disconnection logs
      log_hostname: "off" # Avoided logging hostnames
      log_temp_files: "1024" # Log temp files larger than 1MB
      log_lock_waits: "on" # Keep "on" if monitoring for lock waits
      log_checkpoints: "on" # Keep "on" for checkpointing information
      shared_buffers: 256MB
      pg_stat_statements.max: '10000'
      pgaudit.log_catalog: "off"
      pgaudit.log_parameter: "on"
      pgaudit.log_relation: "on"
      log_statement: "none"

  enablePDB: true


  inheritedMetadata:
    annotations:
      proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
      sidecar.istio.io/proxyCPU: 50m
      sidecar.istio.io/proxyMemory: 112Mi

