apiVersion: artifactregistry.cnrm.cloud.google.com/v1beta1
kind: ArtifactRegistryRepository
metadata:
  name: hopic-k8s-images
  namespace: cnrm-system
  annotations:
    cnrm.cloud.google.com/state-into-spec: merge
spec:
  description: Artifact registry for HoPiC docker images
  format: DOCKER
  location: northamerica-northeast1
  mode: STANDARD_REPOSITORY
