apiVersion: artifactregistry.cnrm.cloud.google.com/v1beta1
kind: ArtifactRegistryRepository
metadata:
  name: hopic-k8s-images
  namespace: configconnector-resources
spec:
  description: Artifact registry for HoPiC docker images
  format: DOCKER
  location: northamerica-northeast1
  mode: STANDARD_REPOSITORY
  cleanupPolicies:
  - action: DELETE
    id: delete-older-than-30-days
    condition:
      olderThan: 2592000s # 30 days
  - action: KEEP
    id: keep-5-recent-versions
    mostRecentVersions:
      keepCount: 5
  cleanupPolicyDryRun: false
