apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  # StorageBucket names must be globally unique
  name: hopic-postgres-backup-01hp04dtnkf
  namespace: cnrm-system
  annotations:
    cnrm.cloud.google.com/force-destroy: "false"
    cnrm.cloud.google.com/deletion-policy: abandon
spec:
  location: northamerica-northeast1
  versioning:
    enabled: true
  storageClass: STANDARD
  uniformBucketLevelAccess: true
---
apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  # StorageBucket names must be globally unique
  name: hopic-test-coverage-reports-01hp04dtnkf
  namespace: cnrm-system
  annotations:
    cnrm.cloud.google.com/force-destroy: "false"
    cnrm.cloud.google.com/deletion-policy: abandon
spec:
  location: northamerica-northeast1
  versioning:
    enabled: true
  storageClass: STANDARD
  uniformBucketLevelAccess: true
