apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: hopic-external-ip
  namespace: cnrm-system
  annotations:
    cnrm.cloud.google.com/state-into-spec: merge
spec:
  addressType: EXTERNAL
  description: HoPiC external ip address for ingress gateway
  location: northamerica-northeast1
  networkTier: STANDARD
---
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSManagedZone
metadata:
  name: hopic-ops-managed-zone
  namespace: cnrm-system
spec:
  cloudLoggingConfig:
    enableLogging: true
  description: HoPiC DNS Zone for alpha DNS
  dnsName: hopic-sdpac.data-donnes.phac-aspc.gc.ca.
  visibility: public
---
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: hopic-ops-dns-record-set
  namespace: cnrm-system
spec:
  name: "hopic-sdpac.data-donnes.phac-aspc.gc.ca."
  type: A
  ttl: 300
  managedZoneRef:
    name: hopic-ops-managed-zone
  rrdatasRefs:
    - name: hopic-external-ip
      kind: ComputeAddress
---
# ephemeral DNS config
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: hopic-ops-ephemeral-dns-record-set
  namespace: cnrm-system
spec:
  name: "*.dev.hopic-sdpac.data-donnes.phac-aspc.gc.ca."
  type: A
  ttl: 300
  managedZoneRef:
    name: hopic-ops-managed-zone
  rrdatasRefs:
    - name: hopic-external-ip
      kind: ComputeAddress
---
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSManagedZone
metadata:
  name: hopic-uni-managed-zone
  namespace: cnrm-system
spec:
  cloudLoggingConfig:
    enableLogging: true
  description: HoPiC DNS Zone for production DNS
  dnsName: hopic-sdpac.data.phac.gc.ca.
  visibility: public
---
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: hopic-uni-dns-record-set
  namespace: cnrm-system
spec:
  name: "hopic-sdpac.data.phac.gc.ca."
  type: A
  ttl: 300
  managedZoneRef:
    name: hopic-uni-managed-zone
  rrdatasRefs:
    - name: hopic-external-ip
      kind: ComputeAddress
---
# ephemeral DNS config
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: hopic-uni-ephemeral-dns-record-set
  namespace: cnrm-system
spec:
  name: "*.dev.hopic-sdpac.data.phac.gc.ca."
  type: A
  ttl: 300
  managedZoneRef:
    name: hopic-uni-managed-zone
  rrdatasRefs:
    - name: hopic-external-ip
      kind: ComputeAddress
