apiVersion: kms.cnrm.cloud.google.com/v1beta1
kind: KMSCryptoKey
metadata:
  name: sops-flux-key
  namespace: cnrm-system
  labels:
    vanity-name: "pht-hopic"
    classification: ucll
spec:
  keyRingRef:
    name: sops
---
apiVersion: kms.cnrm.cloud.google.com/v1beta1
kind: KMSKeyRing
metadata:
  name: sops
  namespace: cnrm-system
  labels:
    vanity-name: "pht-hopic"
    classification: ucll
spec:
  location: northamerica-northeast1
