apiVersion: kms.cnrm.cloud.google.com/v1beta1
kind: KMSCryptoKey
metadata:
  name: sops-flux-key
  namespace: configconnector-resources
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
spec:
  keyRingRef:
    name: sops
  # needs to be seconds as per https://cloud.google.com/config-connector/docs/reference/resource-docs/kms/kmscryptokey#spec
  rotationPeriod: 5184000s # 60days
---
apiVersion: kms.cnrm.cloud.google.com/v1beta1
kind: KMSKeyRing
metadata:
  name: sops
  namespace: configconnector-resources
spec:
  location: northamerica-northeast1
