apiVersion: kms.cnrm.cloud.google.com/v1beta1
kind: KMSCryptoKey
metadata:
  name: sops-flux-key
  namespace: cnrm-system
spec:
  keyRingRef:
    name: sops
---
apiVersion: kms.cnrm.cloud.google.com/v1beta1
kind: KMSKeyRing
metadata:
  name: sops
  namespace: cnrm-system
spec:
  location: northamerica-northeast1
