apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: proxy-only-subnet
  namespace: configconnector-resources
spec:
  ipCidrRange: 10.129.0.0/23
  region: northamerica-northeast1
  description: To allocate source addresses of packets sent from the load balancers to service backends
  networkRef:
    external: projects/pht-01hp04dtnkf/global/networks/hopic-net
  role: ACTIVE
  purpose: REGIONAL_MANAGED_PROXY
