apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: gcr-credentials-sync
  namespace: cnrm-system
spec:
  displayName: gcr-credentials-sync
  description: To obtain artifact registry credentials for image reconciliations in Flux
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: dns01-solver
  namespace: cnrm-system
spec:
  displayName: dns01-solver
  description: To complete DNS01 Challenge for cert-manager
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: hopic-postgres-backup
  namespace: cnrm-system
spec:
  displayName: hopic-postgres-backup
  description: To backup cloudnative postgres in a gcp bucket
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: sops-kms
  namespace: cnrm-system
spec:
  displayName: sops-kms
  description: To decrypt secrets within flux kustomize controller
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: server-deployment
  namespace: cnrm-system
spec:
  displayName: server-deployment
  description: To assign cloud permissions for server deployment in GKE
