# this file is not synced with flux
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: postgres14-cluster-backup
  namespace: server
spec:
  cluster:
    name: cpho-postgres14-cluster
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres14-cluster-scheduled-backup
  namespace: server
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: cpho-postgres14-cluster
