---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: frontend
  namespace: flux-system
spec:
  image: northamerica-northeast1-docker.pkg.dev/pdcp-cloud-006-cpho/cpho/frontend
  interval: 1m0s

