---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: frontend
  namespace: flux-system
spec:
  healthChecks:
  - kind: Deployment
    name: istio-ingressgateway
    namespace: istio-system
  interval: 1m0s
  path: ./frontend
  prune: false
  sourceRef:
    kind: GitRepository
    name: github-repo
  timeout: 2m0s

