---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ingress
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./istio
  prune: false
  sourceRef:
    kind: GitRepository
    name: github-repo

