apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml

patches:
# Using the minimum pod resources https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-resource-requests#compute-class-min-max
  - target:
      kind: Deployment
      name: "(source-controller|image-reflector-controller|image-automation-controller|notification-controller)"
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: all
      spec:
        template:
          spec:
            containers:
              - name: manager
                resources:
                  requests:
                    cpu: 50m
                    memory: 112Mi

  - target:
      kind: Deployment
      name: kustomize-controller
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: kustomize-controller
        namespace: flux-system
      spec:
        template:
          spec:
            containers:
              - name: manager
                resources:
                  requests:
                    cpu: 150m
                    memory: 112Mi
  # patch kustomize-controller service account to access GCP KMS for decrypting secrets
  # See https://fluxcd.io/flux/guides/mozilla-sops/#google-cloud
  - patch: |
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: kustomize-controller
        namespace: flux-system
        annotations:
          iam.gke.io/gcp-service-account: sops-kms@pht-01hp04dtnkf.iam.gserviceaccount.com
    target:
      kind: ServiceAccount
      name: kustomize-controller

  # patch image-reflector-controller service account to access artifact registry
  # See https://fluxcd.io/flux/components/image/imagerepositories/#provider
  - patch: |
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: image-reflector-controller
        namespace: flux-system
        annotations:
          iam.gke.io/gcp-service-account: gcr-credentials-sync@pht-01hp04dtnkf.iam.gserviceaccount.com
    target:
      kind: ServiceAccount
      name: image-reflector-controller
