apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- gcr-sync.yaml

patches:
# Using the minimum pod resources https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-resource-requests#compute-class-min-max
  - target:
      kind: Deployment
      name: "(kustomize-controller|source-controller|image-reflector-controller|image-automation-controller|notification-controller)"
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: all
      spec:
        template:
          spec:
            containers:
              - name: manager
                resources:
                  requests:
                    cpu: 250m
                    memory: 512Mi
  # patch kustomize-controller service account to access GCP KMS for decrypting secrets
  # See https://fluxcd.io/flux/guides/mozilla-sops/#google-cloud
  - patch: |
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: kustomize-controller
        namespace: flux-system
        annotations:
          iam.gke.io/gcp-service-account: sops-kms@pht-01hhjj7tt0m.iam.gserviceaccount.com      
    target:
      kind: ServiceAccount
      name: kustomize-controller
  - patch: |
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: gcr-credentials-sync
        namespace: flux-system
        annotations:
          iam.gke.io/gcp-service-account: gcr-credentials-sync@pht-01hhjj7tt0m.iam.gserviceaccount.com
    target:
      kind: ServiceAccount
      name: gcr-credentials-sync
  # Use chainguard images
  - target:
      kind: Deployment
      name: "kustomize-controller"
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: kustomize-controller
      spec:
        template:
          spec:
            containers:
              - name: manager
                image: cgr.dev/chainguard/flux-kustomize-controller:latest
  - target:
      kind: Deployment
      name: "image-automation-controller"
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "image-automation-controller"
      spec:
        template:
          spec:
            containers:
              - name: manager
                image: cgr.dev/chainguard/flux-image-automation-controller:latest
  - target:
      kind: Deployment
      name: "image-reflector-controller"
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "image-reflector-controller"
      spec:
        template:
          spec:
            containers:
              - name: manager
                image: cgr.dev/chainguard/flux-image-reflector-controller:latest
  - target:
      kind: Deployment
      name: "source-controller"
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "source-controller"
      spec:
        template:
          spec:
            containers:
              - name: manager
                image: cgr.dev/chainguard/flux-source-controller:latest
  - target:
      kind: Deployment
      name: "notification-controller"
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "notification-controller"
      spec:
        template:
          spec:
            containers:
              - name: manager
                image: cgr.dev/chainguard/flux-notification-controller:latest
