apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- gcr-sync.yaml

patches:
  # enable istio injection for the namespace
  - target:
      kind: Namespace
      name: flux-system
    # use ~1 instead of / in path (see https://github.com/kubernetes-sigs/kustomize/issues/1256)
    patch: |-
      - op: add
        path: /metadata/labels/istio.io~1rev
        value: asm-managed
# Using the minimum pod resources https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-resource-requests#compute-class-min-max
  - target:
      kind: Deployment
      name: "(kustomize-controller|helm-controller|source-controller|image-reflector-controller|image-automation-controller|notification-controller)"
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: all
      spec:
        template:
          spec:
            containers:
              - name: manager
                resources:
                  requests:
                    cpu: 200m
                    memory: 400Mi
              - name: istio-proxy
                image: auto
                resources:
                  requests:
                    cpu: 50m
                    memory: 112Mi
  # patch kustomize-controller service account to access GCP KMS for decrypting secrets
  # See https://fluxcd.io/flux/guides/mozilla-sops/#google-cloud
  - patch: |
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: kustomize-controller
        namespace: flux-system
        annotations:
          iam.gke.io/gcp-service-account: sops-kms@phx-01h4rr1468rj3v5k60b1vserd3.iam.gserviceaccount.com      
    target:
      kind: ServiceAccount
      name: kustomize-controller
