---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://bitnami-labs.github.io/sealed-secrets
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  chart:
    spec:
      chart: sealed-secrets
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
      version: '>=1.15.0-0'
  values:
    podAnnotations:
      sidecar.istio.io/proxyCPU: 50m
      sidecar.istio.io/proxyMemory: 112Mi
    resources:
      # TODO: the resulting pod ends up with more than the current requested resources for
      # the sealed-secrets-controller container. Confirmed that these values are used, because
      # increasing them _will_ increase the container resources, it's just that something in
      # GKE autopilot's management of this pod is resulting in more-than-minimum resources
      # assigned to the pod, which then end up added on to the default container (sealed-secrets-controller)
      requests:
        cpu: 200m
        memory: 400Mi
  install:
    crds: Create
  interval: 1h0m0s
  releaseName: sealed-secrets-controller
  targetNamespace: flux-system
  upgrade:
    crds: CreateReplace
