apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-bot-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgARAOAFoCRHsPrZlCKPRJBbKqhZCcjVrXSA8fNZ/Oj3vNH83S/f8oDpcDf6JNqIj2nZKyJXQ8SYmHM23V8HfbbIA3GoaKfQnQBTawrOJI09sCwuH+KpTJ2S5CT/g3A0xGUqcLbrPLMdsRnwCU89Vf1yykbQW9G8gw3B8NK4EIEOaC24baxReaXhLMZ1YY7Ic/3tAGlEiGNPODcgyRwZDZu/Y4OGIanKuR0m8dUR8JwVoRcnDHEjDE5mYJTW/STDtghCAYyLiDmCvBs7WKF5TSS0PckI8K1xn65fu707aBqMrTOIQKGxiFjDLTKZ73AKNKUM2MvPZT0hRnYQ8wvjRR7PF/ccHyE6ElZpOcB5fbcnOTQTy7w1jDctCzIQX6HlhXUYRXy8tpVxe1wR94ydi9BJFCEAcRVRZRjnLqBAQy3h247peG0ku8Leo14/AKnH5W7j1x2xIivXVypshMGyZ3XchXPSbraHOzZgawWG3p/lAlarKyWIXJfPb5RTgvCSmq6mPXiYyo71pcoIs1gXazIBExNkBlfL7QBiXE07IgIW3ndBBzFU6vwMuHuQSVd3C1QF/Mu3XRTnLpJ22/hsTXpC5q6YWWh1eKkBFa6u3zPxkwqNWQ5r0lq6X1P+CQLCwMqqae3pNknUDSgJeBahf3kFC74EfSPAVcqMXnyKee8KobhA4O3AlsCLLwnWCf0BNVXKc75Hx0ZzwQTSK1gEz2Uq3b1MV7pdtB04kwWyQeAzvsW3HO7aJYsGQIvsthhgaTZSy8S7KyGuNg==
  template:
    metadata:
      creationTimestamp: null
      name: slack-bot-token
      namespace: flux-system
---
