apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-cert
  namespace: istio-ingress
spec:
  dnsNames:
    - hopic-sdpac.data-donnes.phac-aspc.gc.ca
    - "*.dev.hopic-sdpac.data-donnes.phac-aspc.gc.ca"
  issuerRef:
    kind: ClusterIssuer
    # name: letsencrypt-staging
    name: letsencrypt
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
    rotationPolicy: Always
  secretName: tlskeys
