apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-cert
  namespace: istio-ingress
spec:
  dnsNames:
    - hopic-sdpac.phac-aspc.alpha.canada.ca
    - "*.eph.hopic-sdpac.phac-aspc.alpha.canada.ca"
  issuerRef:
    kind: ClusterIssuer
    # name: letsencrypt-staging
    name: letsencrypt
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 4096
  secretName: tlskeys
