name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: "Test server Dockerfile build"
        run: cd server && docker build .
      - name: "Test frontend Dockerfile build"
        run: cd frontend && docker build .
